language: ruby
git:
  depth: 1
rvm: 2.4.1
before_script: gem install awesome_bot
script: find -name "*.adoc" -print0 | xargs -0 awesome_bot --allow 302 --allow-dupe --white-list 'http://localhost:8080,http://localhost:8080/api/v1/game/,http://myservice.dauphine.fr,https://whale.imag.fr/'
notifications:
  email: false

