= 2D Library
Génération d’assemblages de couvertures de livres en SVG

== Contexte
Beaucoup de lecteurs migrent aux livres électroniques. Un inconvénient des livres immatériels par rapport aux livres papier est qu’il devient difficile de montrer les livres qu’on a apprécié à ses visiteurs, un rôle que remplissait la bibliothèque physique où on pouvait ranger les livres lus et à lire.

Ce projet vise à donner aux livres immatériels une existence en deux dimensions.

Concrètement, il s’agira de générer des dessins représentant une bibliothèque, où les livres sont vus depuis leur tranche. L’usage envisagé est d’afficher ces dessins sur des écrans, ou de les imprimer en A3, ou en poster (qui pourrait être offert en cadeau), …

== Récits utilisateur
* Génération d’une tranche de livre simple à partir de données statiques : titre, auteur, couleur aléatoire.
* Import de données bibliographiques depuis le web : voir références dans link:biblio.md[biblio].
* Génération de plusieurs rangées de tranches de livres.
* L’utilisateur peut entrer les livres à utiliser comme source.
* L’utilisateur peut indiquer ses préférences : tranche, face, format de chaque livre, format poster, police, couleur, etc.
* Import du vrai format d’un livre.
* Carte d’origine des auteurs, des éditeurs, au bout de chaque rayon.
* Ajout de décors : objets qui trainent devant les livres, certains livres de face devant les autres…

== Dessins
Voir répertoire link:2d_library[] pour inspiration.

