= Collaborative exams
Mise au point collaborative de questionnaires

== Contexte
Ce projet permettra à des enseignants de créer des ensembles de questions et réponses. Ces questions peuvent être réutilisées par d’autres enseignants et combinées pour créer des questionnaires ou des sondages. Les étudiants pourront se servir de ces ensembles de questions pour s’entrainer.

L’application laissera la place à la subjectivité des enseignants, en leur permettant par exemple de privilégier certaines questions.

== Récits utilisateur
* Schéma BD pour stocker une question. Une question comprend un énoncé (« phrasing »), un ensemble de réponses possibles, chacune associée à l’information indiquant si cette réponse est correcte, un identifiant (créé par l’auteur de la question), et un auteur. Un énoncé et une réponse sont des textes simples. L’ensemble de réponses peut être remplacé par une information « Y/N » ou « T/F » ou « free », indiquant une question oui / non, ou vrai / faux, ou de réponse libre. Une question a une langue associée.
* Possibilité de créer une question. Les questions sont immuables, dans ce projet.
* Affichage d’une question.
* Possibilité de créer une variante d’une question (éventuellement d’un autre auteur). Lors d’une création d’une variante, le créateur repart d’une question existante au lieu de partir de zéro.
* Possibilité de spécifier une relation lors de la création d’une variante. Le créateur indique s’il pense que la question interroge sur la même compétence, donc s’il ne faut jamais qu’elles figurent dans le même test. Le créateur indique, si la question interroge sur la même compétence, si la nouvelle variante est plus subtile, moins subtile, aussi subtile, ou ni l’un ni l’autre. (On pourra stocker une relation « at least as subtle as ».) Une question est au moins aussi subtile que sa variante ssi la connaissance de la réponse à la première question implique nécessairement la connaissance de la réponse à la deuxième. Exemples de variantes aussi subtiles : une reformulation dans un autre style littéraire, ou une traduction.
* Possibilité d’améliorer une question. Une amélioration est une variante d’un autre type, où le créateur indique qu’il considère sa formulation objectivement meilleure. (On pourra stocker une relation « objectively better than ».) Ceci implique une interrogation sur la même compétence. Exemples : correction d’une faute d’orthographe ; correction d’une réponse erronée.
* Possibilité d’écrire l’énoncé et la réponse en Asciidoc.
* Affichage de la différence entre une variante et la question originale.
* Un utilisateur peut créer un identifiant personnel pour une question (qui peut lui permettre de s’y retrouver plus facilement qu’en utilisant les identifiants originaux). La paire (identifiant, auteur) doit être unique. C’est alors cet identifiant qui s’affichera pour lui, pour tout ce qui concerne cette question. (Si conflit avec un identifiant non renommé, il faut afficher l’identifiant accompagné de l’auteur original pour l’identifiant non renommé.)
* Un utilisateur peut indiquer s’il trouve qu’une question est une améloration objective d’une autre, ou interroge sur la même compétence (et indiquer la relation de subtilité). Ceci même si l’utilisateur n’est auteur d’aucune des deux questions et même si les questions n’ont pas été créées comme des variantes l’une de l’autre.
* On peut afficher ce que pensent tous les utilisateurs de la relation entre deux questions.
* Un utilisateur peut grouper un ensemble de questions dans un sujet, portant un nom (exemple : « analyse »).
* Ce sujet s’affiche comme « analyse-user » pour les autres utilisateurs, indiquant qu’il s’agit de l’opinion de cet utilisateur.
* Un utilisateur peut déclarer qu’il trouve que les questions marquées par untel comme étant de tel sujet sont de tel sujet (éventuellement différent), à son avis. Il peut cependant soustraire certaines questions de cet ensemble. (Exemple : le sujet « Java » regroupe, à mon avis, toutes les questions marquées « programmation » par Untel sauf les questions q1 et q2.) Cet ensemble s’ajuste lorsque l’utilisateur suivi modifie son opinion.
* Un utilisateur peut créer un questionnaire : il sélectionne un ensemble de questions (provenant éventuellement de différents sujets).
* Un utilisateur peut indiquer un coefficient pour chaque question (pour le calcul de la note).
* Un utilisateur peut créer un modèle de questionnaire : il indique combien de questions doivent être tirées de quels sujet, avec éventuellement une probabilité de tirage pour chaque question au sein d’un sujet donné pour ce questionnaire.
* Un utilisateur peut utiliser un modèle de questionnaire pour générer un ou plusieurs questionnaires.
* Un utilisateur peut modifier un questionnaire (créé manuellement ou généré).
* Affichage d’un questionnaire (généré sur le champ ou précédemment) et recueil des réponses de l’étudiant.
* Affichage de la note de l’étudiant à l’issue du questionnaire.
* Affichage d’une correction à l’issue du questionnaire.
* Un utilisateur peut indiquer à quels autres utilisateurs il fait confiance. Cela a un impact uniquement sur les relations. Un utilisateur se fait toujours confiance.
* Calcul de relations résultantes : l’affichage indique à l’utilisateur, et prend en compte les relations qui sont soit plébiscitées par au moins 80% des utilisateurs, soit indiquées par des utilisateurs auxquels il fait confiance et contredites par moins de 20% des utilisateurs.
* Export d’un questionnaire en XML.
* Export d’un questionnaire en PDF.
* Possibilité de créer des questions et des questionnaires en local plutôt que en ligne (via client lourd). Pour éviter que les étudiants voient les questions avant l’examen.
* Possibilité d’envoyer en ligne des questions et questionnaires créés localement.
* Un utilisateur peut indiquer une relation de préférence subjective entre deux questions. Dans ce cas il ne prétend pas que l’une est objectivement meilleure que l’autre, mais il souhaite néanmoins que la moins bonne ne soit jamais prise dans un questionnaire.

== Nom technique du projet
collaborative_exams

