= J-Voting

Application de manipulation et visualisation de données de vote

== Contexte
La théorie du choix social étudie les propriétés et mises en œuvre de méthodes de vote variées. Une méthode de vote, dans ce contexte, est une façon d’agréger les préférences des électeurs de façon à en déduire une préférence de la société (un choix, ou un rangement, typiquement). Ce projet a pour but de permettre la visualisation de données d’élections, de les manipuler, et de tester des méthodes.

Il s’agira d’améliorer et étendre un https://github.com/oliviercailloux/J-Voting[projet] actuellement utilisé https://github.com/oliviercailloux/j-rank-vectors[comme] https://github.com/oliviercailloux/minimax[base] pour des articles de recherche. Le projet permet la manipulation de préférences de base et l’édition de certaines formes de préférence, ainsi que l’import depuis une feuille de calcul et depuis des formats standards.

== Documentation
Dans ce projet, un ensemble de candidats, d’objets, appelés _alternatives_, est envisagé pour un choix collectif. L’élection présidentielle en France en est un exemple, où les alternatives sont les candidats aux présidentielles. Le choix d’un restaurant entre un groupe d’amis est un autre exemple, où divers restaurants constitueront l’ensemble des alternatives. Un ensemble d’_électeurs_ (voters en anglais) expriment leurs préférences sur cet ensemble d’alternatives. Contrairement à l’élection présidentielle, on envisage ici qu’on connait le classement de chaque électeur sur les alternatives. Ainsi, on sait que l’électeur 1 classe le candidat C avant le candidat B, lui-même avant le candidat D, et le candidat A en dernier, par exemple. Une _règle de vote_ est une fonction associant à chaque ensemble de préférences (associées aux électeurs) un ou plusieurs gagnants ex-æquo.

Le projet doit permettre la manipulation de telles préférences, et leur _aggrégation_ en vue de déterminer un vainqueur, en utilisant l’une des nombreuses règles de vote définies par les chercheurs en choix social.

Diverses restrictions peuvent s’appliquer sur les préférences exprimées par les électeurs : elles peuvent être complètes (pour chaque paire de candidat, on sait que l’un est au moins aussi bon que l’autre), anti-symétriques (pas d’ex-æquo), …

Pour représenter une préférence, on définit généralement une relation de préférence « au moins aussi bon que », considérée comme transitive (donc si A est au moins aussi bon que B, elle-même au moins aussi bonne que C, A est au moins aussi bon que C). Si un électeur juge le candidat A au moins aussi bon que B, et B au moins aussi bon que A, on dit que A et B sont ex-æquos (pour cet électeur). Si A est au moins aussi bon que B, et B n’est pas au moins aussi bon que A, on dit que A est strictement préféré à B (pour cet électeur, et dans le cas où la relation est entièrement connue). C’est ce genre de relation de préférence qu’on vise à manipuler ici.

Ce https://raw.githubusercontent.com/oliviercailloux/J-Voting/master/Doc/Preferences%20Diagram%20Interface.png[diagramme] montre les sortes de relations de préférences manipulées dans le projet et ce qui les différencie.

== À envisager
* Ajouter `AbstractMutablePreference` dont hérite `Mutable*Preference` et qui ne garantit pas qu’on peut effectivement ajouter quoi que ce soit.
* Ajouter `MutablePreferenceFixedAlternatives`, dont le graphe contient toujours toutes les boucles réflexives.
* Ajouter asStrictGraph() dans Preference, qui renvoie un graphe transitif, asymétrique, sous-graphe de asGraph, qui contient uniquement les paires _(a, b)_ telles que _a_ est strictement préféré à _b_ (c-à-d telles que _(a, b)_ est dans asGraph mais _(b, a)_ n’y est pas).
* Ajouter equals dans ImmutablePreference (et l’implémenter).
* Visualisation des graphes. Exporter une préférence au format DOT (voir https://jgrapht.org/guide/UserOverview#guava-graph-adapter[JGraphT adapter] et éventuellement org.decision_deck.utils.relation.graph.GraphExporter et org.decision_deck.utils.relation.graph.mess.DOTExporterTemp<V, E>, dans https://github.com/oliviercailloux/jmcda-utils[J-MCDA utils]), et puis en SVG. 
* Intégrer à https://github.com/oliviercailloux/minimax/blob/master/src/main/java/io/github/oliviercailloux/j_voting/VoterPartialPreference.java[Minimax]
* Quand on ajoute (a, b), il faut ajouter à la fermeture transitive (c, d) pour tout c au moins aussi bon que a et tout d aussi bon ou moins bon que b.
* Un profil concerne toujours un même ensemble d’alternatives pour tous les électeurs, même dans le cas d’un profil muable incomplet. Un profil peut être vide (aucun électeur), auquel cas il ne concerne aucune alternative.
* ImmutableGeneralProfile: preferences, general, on a shared set of alternatives
* ImmutableProfile: preferences, complete, on a shared set of alternatives
* ImmutableAntiSymmetricProfile: preferences, AS, complete, on a shared set of alternatives.
* GeneralProfile: on a shared set of alternatives (may be increased but not decreased), general.
* Un GUI qui permet d’éditer une préférence (de différentes sortes, un GUI pour chaque sorte), sauvée dans un fichier sur le disque dur au fur et à mesure de l’édition.

== Autres idées
* Exporter un profil au format http://www.preflib.org/data/format.php#soc[SOC] (améliorer l’existant), et dans d’autres formats. Voir http://www.preflib.org/data/format.php#election-data[doc], http://www.preflib.org/data/election/netflix/ED-00004-00000001.soc[exemple]. 
* Convertir un InputStream représentant un profile dans un format Pref Lib en profil. Améliorer pour ce faire ReadProfile. La conversion renvoie un profil aussi contraint que possible, donc par exemple plutôt un AntiSymmetricProfile qu’un Profile si possible. La conversion détecte de quel format il s’agit automatiquement, si possible.
* Une méthode permet de télécharger des données exemple depuis Pref Lib. (Déplacer et améliorer méthode dans ReadProfile.) Le GUI permet d’ouvrir les exemples, de les modifier, et de les enregistrer sur le disque dur.
* Améliorer interface SocialWelfareFunction et créer d’autres interfaces : AntiSymmetricSocialWelfareFunction contient une méthode #aggregate qui envoie un AntiSymmetricCompleteProfile vers une CompletePreference, et étend Function (marquer apply comme dépréciée et invoquer #aggregate); SocialWelfareFunction étend AntiSymmetricSocialWelfareFunction et envoie un CompleteProfile vers une CompletePreference. Améliorer FrenchElection.
* GUI pour voir les résultats d’application d’une SWF sur un profil.
* Le GUI permet d’afficher et d’éditer le nombre d’électeurs qui ont les mêmes préférences. Cela permet de travailler également avec de gros profils.
* Implémenter d’autres règles de votes telles que celles proposées dans Whale4. Elles sont toutes disponibles dans le GUI proposé.
* Étudier les différents formats JSON renvoyés par Whale, les comparer aux données dans les formats correspondants de PrefLib (qui sont le standard établi), et documenter un ou plusieurs formats JSON dans un document rédigé au format Asciidoc et placé à la racine de votre projet, permettant de représenter tout ce que vos formats PrefLib permettent de représenter, et aussi compatible que possible avec le format utilisé par Whale : vous pouvez proposer des améliorations par rapport au format de Whale, mais les différences éventuelles doivent être documentées et justifiées. Si le format utilisé par Whale vous parait bon, vous pouvez le conserver tel quel, mais la documentation sera de toute façon utile car la documentation actuelle de ces formats est sommaire ou inexistante, rendant leur utilisation difficile.
* Prise en charge, partout où du PrefLib est actuellement utilisé dans votre bibliothèque (en entrée ou en sortie) et dans les GUI, du format JSON documenté par la fct ci-dessus. (Le programmeur ou utilisateur peut choisir le format.) Utiliser obligatoirement https://github.com/oliviercailloux/java-course/blob/master/JSON.adoc[JSON Processing] ou JSON B, selon ce qui est le plus approprié, cf. cours.
* L’utilisateur peut visualiser un profil créé dans Whale4.
* L’utilisateur peut visualiser les résultats d’une élection selon d’autres règles (cf. Whale4).
* L’utilisateur peut accéder à un profil au format xmcda-modular.
* Séparer la partie GUI dans un projet propre: J-Voting-GUI

== Refs
* http://www.preflib.org/about.php[{PrefLib}]
* https://whale.imag.fr/[Whale4]
* https://github.com/xmcda-modular[xmcda-modular]
* http://www.spliddit.org/

