= J-Voting

Application de manipulation et visualisation de données de vote

== Contexte
La théorie du choix social étudie les propriétés et mises en œuvre de méthodes de vote variées. Une méthode de vote, dans ce contexte, est une façon d’agréger les préférences des électeurs de façon à en déduire une préférence de la société (un choix, ou un rangement, typiquement). Ce projet a pour but de permettre la visualisation de données d’élections, de les manipuler, et de tester des méthodes.

Il s’agira d’améliorer et étendre un https://github.com/oliviercailloux/J-Voting[projet] actuellement utilisé https://github.com/oliviercailloux/j-rank-vectors[comme] https://github.com/oliviercailloux/minimax[base] pour des articles de recherche.

== Commencer par
* Modifier noms de packages pour préfixe correct
* Prendre en compte warnings Eclipse.
* Mise à jour README pour nouveau group id (retirer ce qui est inadéquat)
* Améliorer toString, equals et hashCode dans toutes les classes où ces méthodes sont présentes
* Passer à JUnit 5

== À envisager
* Passer au parent pom oliviercailloux
* Proposer un ensemble d’interfaces pour des préférences. Une préférence a toujours un Voter associé, qui est le Voter 0 par défaut. Une préférence est un ordre transitif sur des alternatives, et peut être anti-symétrique (pas d’alternatives ex-æquo) et peut être complète (non nécessairement complète permet par exemple : a > b et c > d mais a ? c). Une préférence incomplète peut contenir des points isolés (juste c). Une préférence incomplète peut être muable ou immuable. Une préférence complète est toujours immuable. Ainsi, on obtient huit interfaces : CompletePreference (étend Preference), LinearPreference (étend CompletePreference et est anti-symétrique), Preference (non nécessairement complète, sans opérations de mutation ni garantie d’immuabilité, qui n’est pas destinée à être implémentée), AntiSymmetricPreference (étend Preference), MutablePreference (étend Preference), MutableAntiSymmetricPreference (étend AntiSymmetricPreference), ImmutablePreference (étend Preference), ImmutableAntiSymmetricPreference (étend AntiSymmetricPreference). S’inspirer des classes actuelles pour les méthodes (à simplifier autant que possible !). Les opérations de mutation ne permettent que d’ajouter des paires d’alternatives (a, b) (qui peuvent concerner des alternatives encore inconnues). Renommer (dans une tâche séparée) les classes actuelles Preference et StrictPreference en CompletePreferenceImpl et StrictCompletePreferenceImpl (ou LinearPreferenceImpl). Inclure dans Preference une méthode asGraph() qui retourne la préférence comme un https://github.com/google/guava/wiki/GraphsExplained[graphe] (où b est un successeur de a ssi a est au moins aussi bon que b) et dans CompletePreference une méthode asEquivalenceClasses() qui retourne une ImmutableList dont le premier élément (si la préférence n’est pas vide) est l’ensemble des meilleures alternatives, et ainsi de suite pour les rangs suivants.
* Proposer une implémentation de quelques-unes de ces interfaces. Astuce : commencer par les plus générales (MutablePreference), et implémenter les autres en se reposant sur ces implémentations plus générales. S’inspirer éventuellement de l’implémentation dans https://github.com/oliviercailloux/minimax/blob/master/src/main/java/io/github/oliviercailloux/j_voting/VoterPartialPreference.java[Minimax]. Une option permet de maintenir la fermeture transitive à jour à chaque modification du graphe. (Quand on ajoute (a, b), il faut ajouter à la fermeture transitive (c, d) pour tout c au moins aussi bon que a et tout d aussi bon ou moins bon que b.
* Refléter la nouvelle hiérarchie dans les profils en modifiant les interfaces et classes existantes. Pour éviter les confusions, renommer pour commencer Profile en CompleteProfile, ProfileI en Profile, StrictProfile en AntiSymmetricCompleteProfile, etc. Un profile concerne toujours un même ensemble d’alternatives pour tous les électeurs, même dans le cas d’un profil muable incomplet. Les préférences dans un profil incomplet contiennent toutes les alternatives concernées par le profil. Un profil peut être vide (aucun électeur), auquel cas il ne concerne aucune alternative.
* Un GUI qui permet d’éditer une préférence (de différentes sortes, un GUI pour chaque sorte), sauvée dans un fichier sur le disque dur au fur et à mesure de l’édition.
* Exporter une préférence au format DOT (voir https://jgrapht.org/guide/UserOverview#guava-graph-adapter[JGraphT adapter] et éventuellement org.decision_deck.utils.relation.graph.GraphExporter et org.decision_deck.utils.relation.graph.mess.DOTExporterTemp<V, E>, dans https://github.com/oliviercailloux/jmcda-utils[J-MCDA utils]), et puis en SVG.
* Exporter un profil au format http://www.preflib.org/data/format.php#soc[SOC] (améliorer l’existant), et dans d’autres formats. Voir http://www.preflib.org/data/format.php#election-data[doc], http://www.preflib.org/data/election/netflix/ED-00004-00000001.soc[exemple]. 
* Convertir un InputStream représentant un profile dans un format Pref Lib en profil. Améliorer pour ce faire ReadProfile. La conversion renvoie un profil aussi contraint que possible, donc par exemple plutôt un AntiSymmetricProfile qu’un Profile si possible. La conversion détecte de quel format il s’agit automatiquement, si possible.
* Une méthode permet de télécharger des données exemple depuis Pref Lib. (Déplacer et améliorer méthode dans ReadProfile.) Le GUI permet d’ouvrir les exemples, de les modifier, et de les enregistrer sur le disque dur.
* Améliorer interface SocialWelfareFunction et créer d’autres interfaces : AntiSymmetricSocialWelfareFunction contient une méthode #aggregate qui envoie un AntiSymmetricCompleteProfile vers une CompletePreference, et étend Function (marquer apply comme dépréciée et invoquer #aggregate); SocialWelfareFunction étend AntiSymmetricSocialWelfareFunction et envoie un CompleteProfile vers une CompletePreference. Améliorer FrenchElection.
* GUI pour voir les résultats d’application d’une SWF sur un profil.

== Autres idées
ODSProfile:: Possible d’ouvrir une feuille de calcul (au format ODS) contenant un profil tel que décrit dans EditSOC et d’y lire un profil strict ou profil non strict. Les ex-æquos sont notés en utilisant plusieurs colonnes pour un électeur donné. Utiliser Apache ODF Toolkit (voir https://github.com/oliviercailloux/Test-ODFToolkit-ODS[Test ODFToolkit-ODS]).
EditBigSOC:: Le GUI permet d’afficher et d’éditer le nombre d’électeurs qui ont les mêmes préférences. Cela permet de travailler également avec de gros profils.
MoreRules:: (À faire après Results.) Implémenter d’autres règles de votes telles que celles proposées dans Whale4. Elles sont toutes disponibles dans le GUI proposé dans Results.
DocFormats:: Étudier les différents formats JSON renvoyés par Whale, les comparer aux données dans les formats correspondants de PrefLib (qui sont le standard établi), et documenter un ou plusieurs formats JSON dans un document _obligatoirement_ rédigé au format Asciidoc et placé à la racine de votre projet, permettant de représenter tout ce que vos formats PrefLib permettent de représenter, et aussi compatible que possible avec le format utilisé par Whale : vous pouvez proposer des améliorations par rapport au format de Whale, mais les différences éventuelles doivent être documentées et justifiées. Si le format utilisé par Whale vous parait bon, vous pouvez le conserver tel quel, mais la documentation sera de toute façon utile car la documentation actuelle de ces formats est sommaire ou inexistante, rendant leur utilisation difficile.
JSON:: (À faire après DocFormats.) Prise en charge, partout où du PrefLib est actuellement utilisé dans votre bibliothèque (en entrée ou en sortie) et dans les GUI, du format JSON documenté par la fct ci-dessus. (Le programmeur ou utilisateur peut choisir le format.) Utiliser obligatoirement https://github.com/oliviercailloux/java-course/blob/master/JSON.adoc[JSON Processing] ou JSON B, selon ce qui est le plus approprié, cf. cours.

* L’utilisateur peut visualiser un profil créé dans Whale4.
* L’utilisateur peut visualiser les résultats d’une élection selon d’autres règles (cf. Whale4).
* L’utilisateur peut accéder à un profil au format xmcda-modular.
* Séparer la partie GUI dans un projet propre: J-Voting-GUI

== Refs
* http://www.preflib.org/about.php[{PrefLib}]
* https://whale.imag.fr/[Whale4]
* https://github.com/xmcda-modular[xmcda-modular]
* http://www.spliddit.org/

