= J-Voting
Application de manipulation et visualisation de données de vote

== Contexte
Le champ disciplinaire du choix social étudie les propriétés et mises en œuvre de méthodes de vote variées. Une méthode de vote, dans ce contexte, est une façon d’agréger les préférences des électeurs de façon à en déduire une préférence de la société (un choix, ou un rangement, typiquement). Ce projet a pour but de mettre à disposition une plateforme logicielle permettant de visualiser des données d’élections, de les manipuler, et de tester des méthodes.

== Récits utilisateur
* Format pour représenter des profils de vote. En XML Schema, puis en json. Permettre de représenter tous les formats de PrefLib et de Whale.
* L’utilisateur peut visualiser un profil de vote : un ensemble de candidats, un ensemble de préférences (rangement complet des candidats). La dernière version d’un profil est toujours accessible sur /v1/Px/c/, où x est le n° du profil. (v1 indique la première version de l’API.)
* L’utilisateur peut créer un profil de vote, accessible sur /v1/Px/Vy/, où x est le n° de ce profil (un compteur qui s’incrémente), et y est la version (un autre compteur qui s’incrémente).
* L’utilisateur peut modifier un profil créé précédemment. Le profil résultant est accessible sur /v1/Px/Vy/, avec y la nouvelle version créée.
* L’utilisateur peut indiquer qu’une préférence est dupliquée un certain nombre de fois.
* L’utilisateur peut indiquer une préférence partielle : un rangement partiel des candidats. (Exemple, seul un candidat marqué comme le préféré.)
* L’utilisateur peut consulter un profil dans un format {PrefLib} à l’adresse /v1/Px/Vy/format (ou /v1/Px/c/format).
* L’utilisateur peut visualiser un profil disponible dans {PrefLib} à l’adresse /v1/plx/, où x est l’identifiant des données {PrefLib}.
* L’utilisateur peut visualiser un profil créé dans Whale4 à l’adresse /v1/wlx/, où x est l’identifiant des données Whale4.
* L’utilisateur peut visualiser les résultats d’une élection selon la règle de Borda, à l’adresse /v1/Px/Vy/RBorda/.
* L’utilisateur peut visualiser les résultats d’une élection selon d’autres règles (cf. Whale4).
* L’utilisateur peut exporter les résultats d’une élection selon une règle donnée r, dans un format {PrefLib}, à l’adresse /v1/Px/Vy/Rr/format.
* L’utilisateur peut exporter les résultats d’une élection selon une règle donnée r, au format xmcda-modular, à l’adresse /v1/Px/Vy/Rr/xm.
* Publier une bibliothèque permettant de créer, exporter, importer des profils et des résultats.
* L’utilisateur peut accéder à un profil au format xmcda-modular, à l’adresse /v1/Px/Vy/xm.

== Refs
* http://www.preflib.org/about.php[{PrefLib}]
* http://strokes.imag.fr/whale4/[Whale4]
* https://github.com/xmcda-modular[xmcda-modular]
* http://www.spliddit.org/

== Nom technique du projet
jvoting

