= Dauphine Pole Info
Application de gestion des masters MIAGE de Paris-Dauphine

== Contexte
Le département MIDO propose six masters MIAGE (appelés parcours) : IF, ID, SITN, chacun en formation classique et en formation par apprentissage. Chaque parcours a ses cours, ses enseignants intervenants, etc. Les responsables de ces masters souhaitent disposer d’un outil informatique pour faciliter leur gestion, par exemple, recruter et affecter les enseignants aux cours, affecter les étudiants aux cours facultatifs en fonction de leurs préférences, des places disponibles et des contraintes horaires, etc.

L’outil actuellement utilisé n’est plus maintenu et correspond imparfaitement aux attentes des responsables. Il est demandé de le moderniser et, à terme, de l’enrichir de nouvelles fonctionnalités. Ceci en conservant, dans une phase transitoire, la compatibilité avec l’outil existant.

Plusieurs fonctionnalités importantes dépendent de l’existence de link:OpenData.adoc[Dauphine Open Data]. Ce projet-ci contribuera donc à l’avancement de celui-là.

== Récits utilisateur
* Schéma BD reproduisant le schéma de l’application existante, pour conserver la compatibilité.
* Un responsable peut créer des étudiants : nom, prénom, e-mail, parcours de l’étudiant
* Un responsable peut importer les étudiants depuis DOD (qui viennent s’ajouter aux étudiants entrés à la main).
* Fusion des étudiants entrés à la main et des étudiants importés.
* Enseignants : même chose que étudiants : création manuelle et import.
* Tag d’un moment dans l’histoire qui permet de publier l’état actuel de l’application (affectations, coordonnées…) (l’envoyer à l’open data ou visualiser en JSON).
* Import cours depuis Open Data ou ROF.
* Export JSON des affectations des étudiants à un cours ; des enseignants responsables des cours d’un parcours…
* Un responsable peut indiquer quels cours sont facultatifs et accessibles via quels parcours.
* Un étudiant peut entrer ses préférences concernant les cours facultatifs auxquels il a accès.
* Un responsable peut affecter les étudiants aux cours facultatifs. Ce faisant, il voit combien d’étudiants sont déjà inscrits aux cours, ce qui l’aide à équilibrer la charge.
* Accès à la maquette d’un parcours, générée. (Cf. maquettes existantes.)

== Refs
* http://www.poleinfo3.dauphine.fr/ 
* http://10.30.71.19/PI3/web/app_dev.php/

== Nom technique du projet
pole_info

