= Dauphine Pole Info
Application de gestion des masters MIAGE de Paris-Dauphine

== Contexte
Le département MIDO propose six masters MIAGE (appelés parcours) : IF, ID, SITN, chacun en formation classique et en formation par apprentissage. Chaque parcours a ses cours, ses enseignants intervenants, etc. Les responsables de ces masters souhaitent disposer d’un outil informatique pour faciliter leur gestion, par exemple, recruter et affecter les enseignants aux cours, affecter les étudiants aux cours facultatifs en fonction de leurs préférences, des places disponibles et des contraintes horaires, etc.

L’outil actuellement utilisé n’est plus maintenu et correspond imparfaitement aux attentes des responsables. Il est demandé de le moderniser et, à terme, de l’enrichir de nouvelles fonctionnalités. Ceci en conservant, dans une phase transitoire, la compatibilité avec l’outil existant.

Plusieurs fonctionnalités importantes dépendent de l’existence de link:OpenData.adoc[Dauphine Open Data] (DOD). Ce projet-ci contribuera donc à l’avancement de celui-là.

== Récits utilisateur
* Schéma BD reproduisant le schéma de l’application existante, pour conserver la compatibilité.
* Un utilisateur peut demander (en POST) une sauvegarde de l’état actuel de la BD existante, avec (en option) une étiquette que l’utilisateur choisit.
* Un utilisateur peut voir la liste des sauvegardes créées (dates, étiquettes)
* Un administrateur peut demander de restaurer un état précédent de la BD. Dans ce cas, une sauvegarde de l’état avant restauration est créée automatiquement.
* Un responsable peut créer un étudiant : nom, prénom, e-mail, parcours de l’étudiant. L’étudiant est ajouté à la BD existante.
* Un responsable peut visualiser les étudiants depuis DOD (qui viennent s’ajouter aux étudiants entrés à la main).
* Enseignants : même chose que étudiants : création manuelle et visualisation combinée des éléments de la BD existante et de DOD.
* Lorsqu’un responsable crée un étudiant, l’étudiant créé est ajouté simultanément à DOD en plus de la BD existante.
* Visualisation cours depuis DOD.
* Export JSON des affectations des étudiants à un cours ; des enseignants responsables des cours d’un parcours…
* Envoi des informations à DOD : envoi d’informations en POST de données [user, password, paires de (relation, valeur), liste d’identifiant des personnes qui ont accès à l’information] pour stockage en NoSQL.
* Un responsable peut indiquer quels cours sont facultatifs et accessibles via quels parcours.
* Un étudiant peut entrer ses préférences concernant les cours facultatifs auxquels il a accès.
* Un responsable peut affecter les étudiants aux cours facultatifs. Ce faisant, il voit combien d’étudiants sont déjà inscrits aux cours, ce qui l’aide à équilibrer la charge.
* Accès à la maquette d’un parcours, générée. (Cf. maquettes existantes.)

== Refs
* http://www.poleinfo3.dauphine.fr/ 
* http://10.30.71.19/PI3/web/app_dev.php/
* Le code de link:https://github.com/oliviercailloux/poleinfo3[poleinfo3]

== Nom technique du projet
pole_info

