= Teach spreadsheets
Affectation des enseignants aux cours dans le département MIDO via génération de feuilles de calcul

== Contexte
L’administration de MIDO, un département de Dauphine, utilise actuellement des feuilles de calcul pour affecter les enseignants aux cours à enseigner lors d’une année académique donnée. En vue d’une transition vers des outils plus simples d’emploi, ce projet vise à générer automatiquement des feuilles de calcul intégrant les informations fournies par le département ou récupérées d’autres systèmes d’information. Il pourra éventuellement, à terme, interagir avec le projet https://github.com/oliviercailloux/projets/blob/147731c7366af2cf63ea895a6cce8e58ea137d88/teach_planning.adoc[Teach planning] (M2) développant des fonctionnalités complémentaires.

== Récits utilisateur
* Bibliothèque permet de générer un fichier de https://github.com/oliviercailloux/projets/blob/605b03c6bc4c5d2132238a2002d9aa7a0f6c6baf/Voeux/AA%20-%20Saisie%20des%20voeux%202016-2017.xls[saisie des vœux] (cf. page « Apprentissage »).
* Bibliothèque permet de générer un fichier de saisie avec préférences d’un enseignant et le nombre d’années qu’il a enseigné chaque matière.
* Un enseignant peut indiquer ses préférences et le nombre d’années qu’il a enseigné chaque matière : lecture du fichier canevas, génération de l’interface, l’enseignant entre ses préférences, écriture du fichier excel avec préférences.
* Génération d’un fichier agrégeant les préférences indiquées par plusieurs enseignants (cf. https://github.com/oliviercailloux/projets/blob/605b03c6bc4c5d2132238a2002d9aa7a0f6c6baf/Voeux/Fichier%20Agrégé.pdf[Voeux/Fichier Agrégé.pdf]).
* Un utilisateur peut générer une fiche de service pour l’enseignant de son choix (cf. https://github.com/oliviercailloux/projets/blob/605b03c6bc4c5d2132238a2002d9aa7a0f6c6baf/Voeux/Fiche%20de%20service.png[Voeux/Fiche de service.png]). Les coordonnées ne sont pas affichées. Les matières ne sont pas renseignées, seules des cases vides, comme sur l’illustration.
* L’administration peut générer une fiche de service pour l’enseignant de son choix. Les coordonnées sont affichées.

== Refs
* Cf. application link:Test-ODS[] (utilisant Apache ODFToolkit) pour modification de feuilles de calcul (applicable pour générer un fichier OpenDocument Writer).

