= XM-GUI

Interface graphique permettant d’éditer des problèmes de théorie de la décision et d’envoyer ces problèmes à des services web.

== Contexte
Une série de services web ouverts permet d’utiliser les méthodes d’aide multicritère à la décision. Ils reposent sur le format http://www.decision-deck.org/xmcda/[XMCDA] et sur le logiciel http://www.diviz.org/[diviz], qui permet l’invocation des services sans devoir programmer. L’utilisateur doit cependant fabriquer à la main les fichiers XML d’entrée (ou convertir du CSV), et plus généralement il n’existe pas d’intégration des outils dans un logiciel très simple d’emploi.

== Fonctions demandées
* Suivre le https://www.diviz.org/tutorial.diviz.html[tutoriel] diviz. Examiner l’exemple https://github.com/oliviercailloux/Six-real-cars/[Six real cars] au format XMCDA v2 (X2)
* Créer une classe XMCDASubSchema. Une instance de cette classe décrit les informations nécessaires pour appeler un service web XMCDA donné. Il y aura une instance par service web. Ces informations sont décrites dans le fichier descripteur diviz description.xml (http://www.decision-deck.org/ws/wsd-rankAlternativesValues-RXMCDA.html[exemple]). Les données consistent en une association entre des noms (String représentant le nom de l’entrée) et des types XMCDA (le "xmcda main tag"). Les types XMCDA possibles sont représentés à l’aide d’un Enum XMCDAType (inutile de prévoir toutes les possibilités, incluez un certain nombre de types possibles pour illustrer). Exemple : Alternative, Value, AlternativesValues, etc. La documentation autre présente dans le fichier descripteur n’est pas reprise dans la classe.
* Créer une classe XMCDADataDescription dont une instance contient un ensemble de données XMCDA disponibles dans un certain contexte, soit une List de XMCDAType.
* Créer une classe XMCDAWebServices qui reçoit à la création un ensemble de XMCDASubSchema décrivant des services web diviz et qui, lorsqu’on lui envoie une XMCDADataDescription, renvoie le sous-ensemble de XMCDASubSchema compatibles avec les données, c-à-d ceux qui peut être appelé étant donné les données disponibles : ceux dont toutes les informations requises sont disponibles.
* Classe XMCDAData dont une instance contient une List de Node, décrivant un ensemble de données XMCDA.
* Classe XMCDAServiceCaller permettant d’appeler un service web XMCDA. On lui envoie l’url et le XMCDASubSchema d’un service web et un XMCDAData décrivant les données, et elle renvoie un numéro de ticket. Une autre méthode permet, étant donné le ticket, de récupérer un XMCDAData contenant le résultat de l’appel. Essayer d’abord de faire fonctionner le service web wsd-rankAlternativesValues-RXMCDA (voir https://github.com/oliviercailloux/test-call-xmcda-ws[test-call-xmcda-ws] et code existant).
* Classe XMCDASimpleServiceCaller à laquelle on envoie une url, un XMCDASubSchema et un XMCDAData, et qui renvoie un Future permettant d’obtenir le résultat attendu. La tâche créée interroge le service web (pour savoir si le travail est terminé) d’abord toutes les deux secondes pendant les premières dix secondes, puis toutes les dix secondes pendant la première minute, puis toutes les minutes.
* GUI spécifiques pour éditer différents types XMCDA. Un GUI par type. Le GUI lit et sauvegarde les données au format X2. Utiliser la bibliothèque https://github.com/oliviercailloux/XMCDA-2.2.1-JAXB/[XMCDA-2.2.1-JAXB] et repartir du code existant pour les cas déjà traités. Le GUI est associé à un fichier dans le répertoire courant déterminé une fois pour toutes au lancement, par exemple `alternatives.xml`.
* GUI permettant de créer, importer, éditer différents types XMCDA simultanément. Ce GUI appelle les GUI spécifiques (placés dans des onglets) et permet en plus de lister tous les services web compatibles avec les données présentes, et d’en appeler un et de visualiser le résultat.
* Parsing d’un fichier de description diviz description.xml (http://www.decision-deck.org/ws/wsd-rankAlternativesValues-RXMCDA.html[exemple]) et création d’un XMCDASubSchema correspondant à l’entrée et un correspondant à la sortie.
* Prendre en charge Alternative, Criterion, et un ensemble d’évaluations au format https://github.com/xmcda-modular[XMCDA-modular] (XM, utiliser la bibliothèque JAXB) : sérialisation et déserialisation. On pourra donc facilement convertir une entrée X2 en sortie XM, ou l’inverse.

