= XM-GUI

Intrerface graphique permettant d’éditer des problèmes de théorie de la décision et d’envoyer ces problèmes à des services web.

== Contexte
Une série de services web ouverts permet d’utiliser les méthodes d’aide multicritère à la décision. Ils reposent sur le format XMCDA et sur le logiciel https://www.diviz.org/tutorial.diviz.html[Diviz], qui permet l’invocation des services sans devoir programmer. L’utilisateur doit cependant fabriquer à la main les fichiers XML d’entrée (ou convertir du CSV), et plus généralement il n’existe pas d’intégration des outils dans un logiciel très simple d’emploi.

== Fonctions demandées
Contract1:: Une classe Alternative (immuable, contenant un simple entier l’identifiant) et une classe Criterion (même chose). Une classe MCProblem qui stocke un problème d’aide multicritère à la décision : un ensemble d’alternatives, un ensemble de critères, une table d’évaluation. Une table d’évaluation associe à chaque paire (alternative, critère) un double. Utiliser pour ce faire une https://github.com/google/guava/wiki/NewCollectionTypesExplained#table[Table] Guava. (2)
Contract2:: Une classe AlternativesRanking, qui contient un ensemble d’alternatives chacune associée à son rang. On pourra utiliser une Multimap Guava (associer le rang à toutes les alternatives de ce rang). Par exemple, on pourra utiliser une instance de cette classe pour stocker : a1 > {a2, a3} > a4, voulant dire que a1 est au rang 1, a2 et a3 sont ex-æquo au rang 2, et a4 est au rang 3. (1)
File1:: Une classe qui permet de lire et écrire une Alternative, un Criterion, et un ensemble d’évaluations au format X2 (XMCDA v2, voir lien ci-dessous). (2)
File2:: Une classe qui permet de lire et écrire une instance de AlternativesRanking au format X2, dans l’élément `alternativesValues` : une entrée par alternative, contenant son rang. (1)
Resources1:: Inclure dans votre class path un fichier exemple au format X2. Créer une méthode main qui lit le fichier à l’aide de vos méthodes existantes. (0,5)
Resources2:: Inclure dans votre class path un fichier image (plot) obtenu par invocation du service web illustré dans le tutoriel sur Diviz (lien ci-dessus). Créer une méthode main qui crée une fenêtre principale (vide) et affiche l’image à l’aide de SWT (https://www.safaribooksonline.com/library/view/swt-a-developers/0596008384/ch02s09.html[exemple], auquel il faut ajouter un appel à `dispose` pour se débarrasser de l’image en fin de programme). (1)
BasicGUI:: Un GUI basique qui permet l’édition d’un ensemble d’alternatives et de critères à partir de rien (simplement entrer leurs ids) et sauve cette paire d’informations au format X2. Ceci se fait dans deux onglets, un pour les alternatives et un pour les critères. Pas besoin de bouton Save : le programme écrit au fur et à mesure des modifications. (2)
EvaluationsGUI:: Un GUI basique qui permet l’édition d’une table d’évaluations à partir de rien, et sauve ceci au format X2. Pas de bouton Save. Utiliser une Table SWT. (3)
WSCallRank :: Classe permettant d’appeler le service web wsd-rankAlternativesValues-RXMCDA (voir test-call-xmcda-ws), et de récupérer le résultat dans un objet de type AlternativesRanking. (1)
WSCall:: Classe permettant d’appeler le service web de Diviz présenté dans le tutoriel, et de récupérer le résultat dans un objet approprié (tel que https://docs.oracle.com/javase/tutorial/2d/images/[`BufferedImage`]). Généraliser de manière à pouvoir appeler facilement d’autres services web qui ne renvoient qu’un résultat (à part les messages), comme dans le cas de plotNumericPerformanceTable ou wsd-rankAlternativesValues-RXMCDA. (1)
XM:: Prendre en charge Alternative, Criterion, et un ensemble d’évaluations au format XMCDA-modular (XM, voir lien ci-dessous, utiliser la bibliothèque JAXB) : sérialisation et déserialisation. On pourra donc facilement convertir une entrée X2 en sortie XM, ou l’inverse. (1)

== Références
* https://github.com/xmcda-modular[xmcda-modular] sur Github. (Voir schéma et exemple, et bibliothèque JAXB.)
* https://github.com/oliviercailloux/XMCDA-2.2.1-JAXB/[XMCDA-2.2.1-JAXB] : génération et lecture de fichiers au format X2.
* http://www.decision-deck.org/xmcda/[XMCDA], site officiel.
* http://www.diviz.org/[diviz], site officiel.
* http://www.decision-deck.org/ws/wsd-rankAlternativesValues-RXMCDA.html[exemple] de fichier description Diviz: voir description.xml.
* https://github.com/oliviercailloux/test-call-xmcda-ws[test-call-xmcda-ws]
* https://github.com/oliviercailloux/Six-real-cars/[Six real cars] au format X2

