= Cartographie

Le projet a pour but premier de permettre le calcul multi-modal d’itinéraires (utilisant transports en commun ; vélo ; etc.). Plus précisément, il permettra dans un premier temps de calculer le temps de trajet d’un point à un autre de Paris en transport en commun.

S’il s’avère trop difficile à mettre en œuvre, on pourra basculer sur un autre projet.

== Récits utilisateur

* Calcul du temps de trajet en transport en commun depuis Google Map.
* Installation d’un serveur open street map (OSM) servant une carte de Paris.
* Obtention du temps de trajet à pied d’un point à un autre de Paris (via OSM).
* Rapatriement de données GTFS de STIF (voir références ci-dessous).
* Affichage d’un morceau de carte OSM.
* Affichage d’une ligne de transport sur la carte OSM.
* Calcul temps de trajet en transport, sans changement, d’un point à un autre de Paris (via OSM et GTFS).
* Calcul temps de trajet en transport, avec changements.
* Calcul temps de trajet multi-modal.

== Refs
* http://www.geovelo.fr (min risk and min time)
* GTFS : https://wiki.openstreetmap.org/wiki/General_Transit_Feed_Specification https://github.com/OneBusAway/onebusaway-gtfs-modules http://transitfeeds.com/ https://opendata.stif.info/explore/dataset/offre-horaires-tc-gtfs-idf/
http://www.nctr.usf.edu/2011/05/enabling-cost-effective-multimodal-trip-planners-through-open-transit-data-2/
http://www.opentripplanner.org/ 

