= Collaborative exams

Mise au point collaborative de questionnaires

== Contexte
Ce projet permettra à des enseignants de créer des ensembles de questions et réponses. Ces questions peuvent être réutilisées par d’autres enseignants et combinées pour créer des questionnaires ou des sondages. Les étudiants pourront se servir de ces ensembles de questions pour s’entrainer.

L’application laissera la place à la subjectivité des enseignants, en leur permettant par exemple de privilégier certaines questions.

On repartira du https://github.com/oliviercailloux/Collaborative-exams[projet] existant. Il s’agira dans un premier temps de solidifier ses fonctionnalités et d’écrire des tests unitaires. Il faudra également améliorer la relation de hiérarchie entre différentes questions ; et éventuellement corriger les fonctions manquantes telles que `SameAbility`. La dépendance actuelle concernant le DOM devra sans-doute être retirée.

== Fonctions demandées
Question:: Interfaces et objets pour Question et objets associés. Une question comprend un énoncé (« phrasing »), une langue, un ensemble de réponses possibles, chacune associée à l’information indiquant si cette réponse est correcte, un identifiant (int), et un auteur. Un auteur est identifié par un id (int) et a un e-mail. Utiliser un objet Person pour les auteurs. Un énoncé et une réponse sont des textes simples. L’ensemble de réponses peut être remplacé par une information « Y/N » ou « T/F » ou « free », indiquant une question oui / non, ou vrai / faux, ou de réponse libre. Créer à cet effet une interface MultipleChoiceQuestion qui étend Question. L’auteur peut associer un identifiant personnel (string) à une question. Ceci est stocké hors de l’objet Question. Cet identifiant peut changer. (La paire (auteur, identifiant) doit être unique.) Une question est immuable. (2)
QuestionText:: Lecture et écriture d’une question en format JSON. (1)
Servlets:: Servlet NewQuestion(question): id, qui reçoit une question en format JSON ; servlet GetQuestion(id): question, qui envoie une question à partir de son id. (1)
ServletsModify:: ChangeResponseTypeTF(id orig, new author id): new id et ChangeResponseTypeYN(id orig, new author id). Change la réponse à une question en créant une nouvelle question qui a un autre type de réponse (c-à-d Y/N ou T/F) et en renvoyant son nouvel id. ChangeQuestionLanguage(id orig, new author id, new language): new id. (1)
ServletAbilities:: Stocker une relation « same ability » entre questions, associée à une personne. Une personne peut indiquer qu’une question interroge, à son avis, sur la même compétence qu’une autre. (On pourra l’utiliser pour éviter que ces questions figurent dans le même test.) Servlet SameAbility(person id, id question 1, id question 2, sameAbility: boolean) et servlet GetSameAbility(person id, id question 1, id question 2): boolean. La relation est réflexive et symétrique (donc inutile de stocker les parties réflexives et déduire ce qu’on peut de la symétrie). (1)
ServletImprovements:: Stocker une relation « improvement » entre questions, associée à une personne. Une personne peut indiquer qu’une question, à son avis, est meilleure qu’une autre, tout en interrogeant sur les mêmes compétences. Exemples : correction d’une faute d’orthographe ; correction d’une réponse erronée. (On pourra l’utiliser pour présenter uniquement les questions avec les meilleures formulations.) Ceci implique Same ability et At least as subtle as. (1)
BasicClient:: Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande, la création et la visualisation de questions au format asciidoc. Il faudra pouvoir voir le rendu en plus du code source. (1)
ModifClient:: Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande, la création de questions à partir d’autres questions et la modification de relations. (1)
QuestionXML:: Lire et écrire une question en XML, et les relations de votre modèle. Chaque relation peut être représentée comme un ensemble de triplets associé à une personne. (1)
QuestionJSON:: Lire et écrire les relations du modèle en JSON. (0,5)
QuestionMultiFormat:: Récupérer une question à partir de son id, en format XML ou JSON. Introduire une question en multiples formats. Transformer en REST. Cookie permet de mémoriser un id person, il est utilisé si l’id person n’est pas fourni, pour les servlets qui requièrent ce paramètre. (1)
RelationsMultiFormat:: Servlet GetSameAbility(person id): ensemble de triplets ; et de même pour les autres relations, et de même pour Set. La relation peut être récupérée ou envoyée au format XML ou JSON. Cookie permet de mémoriser un id person, il est utilisé si l’id person n’est pas fourni. (1)
Online:: Faire tourner le serveur en ligne grâce au service d’IBM. (0,5)
SetDB1:: Implémenter des entités JPA et les méthodes permettant d’écrire et de lire depuis la BD les questions. (1)
SetDB2:: Même chose pour le reste du modèle : relations, tags, … (1)
UseDB:: Modifier les servlets pour qu’ils écrivent dans et lisent la BD. (1)
Lib:: Isoler la partie bibliothèque du reste du code. La publier comme un projet Maven indépendant (suffixer le nom du projet de -lib) et faire dépendre le reste du code de cette bibliothèque. Isoler la partie client du reste du code, publier comme un projet indépendant (ProjectName-client). Publier la partie serveur comme un projet indépendant (ProjectName). (1,5)
SOAP:: Transformer certains servlets pour en faire des services SOAP. (1)
SOAPClient:: Transformer les clients pour en faire des clients SOAP. (1)

== Autres fonctionnalités
ServletSubtleties:: Stocker une relation « at least as subtle as » entre questions, associée à une personne, et créer un servlet associé. Une personne peut indiquer qu’une question est (à son avis) au moins aussi subtile qu’une autre. Une question est au moins aussi subtile que sa variante ssi la connaissance de la réponse à la première question implique nécessairement la connaissance de la réponse à la deuxième. Exemples de variantes aussi subtiles : une reformulation dans un autre style littéraire, ou une traduction. La relation est réflexive mais bien sûr pas nécessairement symétrique. (1)
PersonalTags:: Chaque personne peut associer un identifiant personnel à chaque question (y compris celles dont la personne n’est pas auteur). La paire (personne, identifiant) doit être unique. Chaque personne peut associer un ensemble de sujets à chaque question (exemple : Math, Java, Programmation). Ces sujets sont personnels. (Donc deux personnes peuvent indiquer des sujets différents pour une même question.) Servlets Get et Set correspondantes. (1)
ExtClient:: Développer un client avec GUI (bien réfléchi) pour créer, modifier, des questions et leurs relations et leur associer des identifiants et sujets personnels. Ajouter les servlets jugées utiles pour ce faire. (3)

* On peut afficher ce que pensent tous les utilisateurs de la relation entre deux questions.
* Récupérer toutes les questions qui portent le sujet S donné par l’utilisateur U. Plus généralement, toutes les questions qui satisfont une certaine requête.
* Un utilisateur peut déclarer qu’il trouve que les questions marquées par untel comme étant de tel sujet sont de tel sujet (éventuellement différent), à son avis. Il peut cependant soustraire certaines questions de cet ensemble. (Exemple : le sujet « Java » regroupe, à mon avis, toutes les questions marquées « programmation » par Untel sauf les questions q1 et q2.) Cet ensemble s’ajuste lorsque l’utilisateur suivi modifie son opinion.
* Un utilisateur peut créer un questionnaire : il sélectionne un ensemble de questions (provenant éventuellement de différents sujets).
* Un utilisateur peut indiquer un coefficient pour chaque question (pour le calcul de la note).
* Un utilisateur peut créer un modèle de questionnaire : il indique combien de questions doivent être tirées de quels sujet, avec éventuellement une probabilité de tirage pour chaque question au sein d’un sujet donné pour ce questionnaire.
* Un utilisateur peut utiliser un modèle de questionnaire pour générer un ou plusieurs questionnaires.
* Un utilisateur peut modifier un questionnaire (créé manuellement ou généré).
* Affichage d’un questionnaire (généré sur le champ ou précédemment) et recueil des réponses de l’étudiant.
* Affichage de la note de l’étudiant à l’issue du questionnaire.
* Affichage d’une correction à l’issue du questionnaire.
* Un utilisateur peut indiquer à quels autres utilisateurs il fait confiance. Cela a un impact uniquement sur les relations. Un utilisateur se fait toujours confiance.
* Calcul de relations résultantes : l’affichage indique à l’utilisateur, et prend en compte les relations qui sont soit plébiscitées par au moins 80% des utilisateurs, soit indiquées par des utilisateurs auxquels il fait confiance et contredites par moins de 20% des utilisateurs.
* Export d’un questionnaire en PDF.
* Possibilité de créer des questions et des questionnaires en local plutôt que en ligne (via client lourd). Pour éviter que les étudiants voient les questions avant l’examen.
* Possibilité d’envoyer en ligne des questions et questionnaires créés localement.
* Un utilisateur peut indiquer une relation de préférence subjective entre deux questions. Dans ce cas il ne prétend pas que l’une est objectivement meilleure que l’autre, mais il souhaite néanmoins que la moins bonne ne soit jamais prise dans un questionnaire.

