= 2D Library

Génération d’assemblages de couvertures de livres en SVG

== Contexte
Beaucoup de lecteurs migrent aux livres électroniques. Un inconvénient des livres immatériels par rapport aux livres papier est qu’il devient difficile de montrer les livres qu’on a apprécié à ses visiteurs, un rôle que remplissait la bibliothèque physique où on pouvait ranger les livres lus et à lire.

Ce projet vise à donner aux livres immatériels une existence en deux dimensions.

Concrètement, il s’agira de générer des dessins représentant une bibliothèque, où les livres sont vus depuis leur tranche. L’usage envisagé est d’afficher ces dessins sur des écrans, ou de les imprimer en A3, ou en poster (qui pourrait être offert en cadeau), …

On repartira d’un https://github.com/oliviercailloux/2D-Library[projet] existant. Il permet de générer une image SVG à partir d’un ensemble de livres et des préférences d’affichage d’un utilisateur : nombre de livres par étagère, livres obliques ou droits et inclinaison… ; de récupérer des données de livres depuis la https://fr.wikipedia.org/wiki/Biblioth%C3%A8que_du_Congr%C3%A8s[Bibliothèque du Congrès] ; il fournit également une interface graphique pour accéder à certaines fonctionnalités.

== À envisager
* Passer à JUnit 5
* Classes immuables, …
* Un livre peut avoir plusieurs auteurs (ordonnés)
* Réduire redondance et améliorer tests unitaires
* Égalité des Library
* Les tailles se calculent automatiquement (hauteur d’un Shelf, hauteur et largeur d’une Library) étant donnés les livres qui s’y trouvent
* Enregistrement (et lecture) des données en JSON : un Book (donner un id à chaque book, sans ajouter l’id à la classe Book); l’ensemble des Book; une Library (positions des books par id); l’ensemble des Library.
* On peut associer des tags décrivant (objectivement) les livres, par exemple le sujet du livre (programmation, …), le type du livre (roman, …). Ces tags permettront de regrouper les livres dans les bibliothèques de l’utilisateur.
* Clarifier le générateur de SVG : une seule méthode publique ; regrouper les données requises et les séparer de la classe SVGLibrary ; commenter où c’est utile et retirer les commentaires inutiles…
* Congress: renvoie un Book ; parser le XML élégamment ; améliorer gestion des exceptions
* Classe représentant des données de recherche d’un livre : nom de l’auteur partiel, titre partiel, et intervalle d’années de publication (par exemple : auteur "Shakesp", titre "Hamlet", années 1580 – 1605)
* Service de recherche de livre dans la bibliothèque du congrès
* Générateur de bibliothèques en fonction des livres de l’utilisateur (par ordre alphabétique, par sujet, par taille, aléatoire…)
* Interface en ligne de commande pour générer un SVG à partir des données JSON de l’utilisateur
* Améliorer GUI : exceptions ; éviter pop-ups (ou plutôt envisager de basculer de Swing à SWT)
* Ajouter GUI séparées uniquement pour édition des livres ; édition des bibliothèques ; édition des tags ; édition des préférences du dessin SVG ; recherche de livre sur le web à partir de données partielles (partie du nom d’auteur, date approximative…) ; puis regrouper
* Web : un serveur qui renvoie un SVG avec les données d’un utilisateur (stockées dans un sous-répertoire dont le nom est donné en paramètre)
* Le serveur affiche le résumé ou d’autres informations, étant donné l’identifiant d’un livre de l’utilisateur
* Stocker dans une BD via Hibernate au lieu des fichiers JSON
* Code QR qui permet de voir les résumés ou d’autres informations
* L’utilisateur peut souhaiter fixer la taille de sa bibliothèque pour commencer (en fonction de l’endroit où il veut afficher le résultat) puis remplir les livres sous contrainte de taille

== Autres idées
* Facebook, partager au sein d’une communauté où mes amis me disent ce qu’ils apprécient, …
* Trier par couleur et associer des couleurs par genre ;
* utiliser comme portail pour la lecture de livres ;
* importer mes epubs que j’ai acheté et les rendre lisibles via l’application
* Tri sur demande de l’utilisateur
* L’utilisateur peut indiquer comme préférences : tranche, face, pour chaque livre
* Import du vrai format d’un livre. (Voir projet existant J-Biblio) Ou édition par l’utilisateur, y compris format, police, …
* Carte d’origine des auteurs, des éditeurs, au bout de chaque rayon.
* Ajout de décors : objets qui trainent devant les livres, certains livres de face devant les autres…
* Afficher uniquement, ou mettre en avant, les nouveautés depuis une certaine date / depuis la dernière visite de qqn

== Dessins
Voir répertoire https://github.com/oliviercailloux/projets/tree/master/2D%20Library[2D Library] pour inspiration.

