= 2D Library

Génération d’assemblages de couvertures de livres en SVG

== Contexte
Beaucoup de lecteurs migrent aux livres électroniques. Un inconvénient des livres immatériels par rapport aux livres papier est qu’il devient difficile de discuter des livres qu’on a apprécié avec ses visiteurs, un rôle que remplissait la bibliothèque physique où on pouvait ranger les livres lus et à lire.

Ce projet vise à donner aux livres immatériels une existence en deux dimensions.

Concrètement, il s’agira de générer des dessins représentant une bibliothèque, où les livres sont vus depuis leur tranche. L’usage envisagé est d’afficher ces dessins sur des écrans ou sur des réseaux sociaux, ou de les imprimer en A3, ou en poster, …

On repartira d’un https://github.com/oliviercailloux/2D-Library[projet] existant. Il permet de générer une image SVG à partir d’un ensemble de livres et des préférences d’affichage d’un utilisateur : nombre de livres par étagère, livres obliques ou droits et inclinaison… ; de récupérer des données de livres depuis la https://fr.wikipedia.org/wiki/Biblioth%C3%A8que_du_Congr%C3%A8s[Bibliothèque du Congrès] ; il fournit également une interface graphique pour accéder à certaines fonctionnalités.

== À envisager
* Rendre immuables les classes du modèle
* Renommer `Library` en `Assembly`, représentant un assemblage spécifique de livres
* Écriture d’un `Assembly` dans `assembly.json` dans le répertoire courant (un utilisateur pourra à terme en avoir plusieurs ; sa bibliothèque étant l’union de tous les livres des assemblages)
* Séparer un ouvrage et sa représentation : `Book` devrait avoir trois dimensions: `height`, `length`, `width`, correspondant aux dimensions de l’ouvrage physique correspondant, ou indisponibles si pas d’ouvrage physique correspondant ; et `BookRepresentation` devrait avoir la couleur, `height` et `length`. Les tailles devraient être des entiers et mesurées en millimètres.
* Pouvoir générer une image SVG à partir du fichier `assembly.json` en ligne de commande
* Simplifier SVGLibrary avec la supposition que l’assembly a déjà toutes les bonnes tailles ; séparer le calcul de taille et la génération de dessin
* GUI SWT pour montrer un assembly
* Création d’une bibliothèque (ensemble de livres) à partir d’un ensemble de fichiers assembly.
* GUI pour création d’une étagère : l’utilisateur choisit et ordonne les livres de sa bibliothèque et voit le dessin de l’étagère résultante. (La taille est calculée automatiquement.) Optionnellement, il peut spécifier pour chaque livre s’il est de face, de profil, en biais, sa couleur… L’étagère est créée dans un fichier `assembly-time.json` avec la date et heure de création
* Ajouter un titre à un Assembly
* GUI pour créer un assembly en associant des étagères. Envisager deux possibilités : l’utilisateur spécifie d’abord la taille de l’assemblage désirée, ou la taille est déduite des étagères présentes
* Congress: renvoie un Book ; parser le XML élégamment ; améliorer gestion des exceptions
* Classe représentant des données de recherche d’un livre : nom de l’auteur partiel, titre partiel, et intervalle d’années de publication (par exemple : auteur "Shakesp", titre "Hamlet", années 1580 – 1605)
* Service de recherche de livre dans la bibliothèque du congrès (ligne de commande)
* GUI pour récupérer des livres de la bibliothèque du congrès et les ajouter à un nouveau fichier assembly
* Pouvoir récupérer des livres depuis d’autres sources
* Pouvoir modifier la hauteur des étagères plutôt que les calculer automatiquement
* Passer à JUnit 5
* Un livre peut avoir plusieurs auteurs (ordonnés)
* Égalité des classes du modèle
* Générateur d’assemblage en fonction des livres de l’utilisateur (par ordre alphabétique, par sujet, par taille, aléatoire…)
* Code QR qui permet de voir les résumés ou d’autres informations
* L’utilisateur peut souhaiter fixer la taille de sa bibliothèque pour commencer (en fonction de l’endroit où il veut afficher le résultat) puis remplir les livres sous contrainte de taille
* Web : un serveur qui renvoie un SVG assemblé à partir d’un assembly json
* Facebook, partager au sein d’une communauté où mes amis me disent ce qu’ils apprécient, …
* Trier par couleur et associer des couleurs par genre ;
* utiliser comme portail pour la lecture de livres ;
* importer mes epubs que j’ai acheté et les rendre lisibles via l’application
* Image interactive qu’on peut trier sur demande
* Édition par l’utilisateur de la représentation : format, police, …
* Carte d’origine des auteurs, des éditeurs, au bout de chaque rayon.
* Ajout de décors : objets qui trainent devant les livres, certains livres de face devant les autres…
* Afficher uniquement, ou mettre en avant, les nouveautés depuis une certaine date / depuis la dernière visite de qqn

== Dessins
Voir répertoire https://github.com/oliviercailloux/projets/tree/master/2D%20Library[2D Library] pour inspiration.

