= J-Voting

Application de manipulation et visualisation de données de vote

== Contexte
Le champ disciplinaire du choix social étudie les propriétés et mises en œuvre de méthodes de vote variées. Une méthode de vote, dans ce contexte, est une façon d’agréger les préférences des électeurs de façon à en déduire une préférence de la société (un choix, ou un rangement, typiquement). Ce projet a pour but de permettre la visualisation de données d’élections, de les manipuler, et de tester des méthodes.

== Fonctions demandées
Contract1:: Une classe immuable Alternative qui contient simplement un id (entier). Une classe immuable StrictPreference qui contient une liste d’alternatives (représentant un rangement par ordre de préférence des alternatives, strict signifiant sans ex-æquo), qui ne contient pas deux fois la même alternative. Une classe immuable Voter qui contient un id (entier). (1)
Contract2:: Une classe StrictProfile qui associe des électeurs à leurs préférences strictes. Ces préférences ne s’expriment pas nécessairement sur le même ensemble d’alternatives. (1)
File1:: Une classe qui permet d’écrire un profil au format http://www.preflib.org/data/format.php#soc[SOC] (strict order, complete). Ne fonctionne que dans le cas où toutes les préférences du profil portent sur les mêmes alternatives. Vous pouvez pour le moment supposer que toutes les préférences sont différentes. Voir http://www.preflib.org/data/format.php#election-data[doc], http://www.preflib.org/data/election/netflix/ED-00004-00000001.soc[exemple]. (1,5)
File2:: Une classe qui permet de lire un profil à partir du format SOC ou SOI. (1)
Resources1:: Inclure dans votre class path un fichier exemple au format SOC. Créer une méthode main qui affiche le contenu du fichier. (Documenter dans le code source la provenance du fichier.) (0,5)
Resources2:: Inclure dans votre class path un fichier exemple au format SOI. Créer une méthode main qui affiche le contenu du fichier. (Documenter dans le code source la provenance du fichier.) (0,5)
Interfaces1:: Créer une Interface Java SocialWelfareFunction. Elle fournit, sur base d’un profil, une préférence : un rangement complet des alternatives présentes dans le profil, par ordre de préférence pour la société. Vous pouvez pour le moment supposer que c’est une préférence stricte. Fusionner dans master. Dans la branche Interfaces1.1, créer une classe SWFCommander. On peut lui fournir une instance de SocialWelfareFunction. Elle fournit une méthode qui demande en boucle à l’utilisateur, sur l’entrée standard, des préférences (supposées entrées au format SOC, une préférence à la fois), et lui renvoie après chaque étape l’agrégation du profil composé des préférences entrées jusque là. Faites en sorte que la branche Interfaces1.1 ne contienne pas d’implémentation de SocialWelfareFunction. (1)
Interfaces2:: Une classe Borda qui implémente SocialWelfareFunction. La méthode de Borda attribue un score à chaque alternative, puis range ces alternatives par ordre décroissant de score. Le score d’une alternative dans une préférence est le nombre d’alternatives qu’elle bat. Le score total d’une alternative est la somme de ses scores sur toutes les préférences. Vous pouvez pour le moment supposer qu’il n’y a que deux alternatives. (En cas d’ex-æquo, renvoyez n’importe quel rangement.) Fusionner Interfaces2 et Interfaces1.1 dans master. Dans la branche Interfaces 2.1, créer une méthode main qui fait fonctionner le programme de discussion avec l’utilisateur. (1)
NonStrict:: Une classe immuable Preference qui permet de représenter un rangement avec ex-æquo. StrictPreference étend Preference. (1)
Struct:: Créer des Interfaces Java ProfileI représentant un profil incomplet, Profile (complet) qui étend ProfileI, StrictProfileI qui étend ProfileI et StrictProfile qui étend Profile et StrictProfileI. Strict signifie que les préférences contenues dans le profil sont strictes. Complet signifie que toutes les préférences dans le profil portent sur les mêmes alternatives, alors que Incomplet indique que cette propriété n’est pas garantie. Renommer la classe existante StrictProfile en StrictProfileBuilder (qui n’implémente aucune de ces interfaces). Créer une classe ImmutableStrictProfile qui implémente StrictProfile. StrictProfileBuilder doit permettre de récupérer une instance de ImmutableStrictProfile. Les interfaces présentent toutes une méthode getPreference(Voter), qui renvoie un objet Preference ou StrictPreference. Adapter le reste du code. (2)
Welfares:: Implémenter Borda correctement et une nouvelle classe, Dictator. Dictator implémente également SocialWelfareFunction. Une méthode supplémentaire lui permet de préciser un des électeurs (le dictateur). La classe renvoie toujours la préférence de cet électeur. (2)
PrefLib:: Étant donné une URL (voir exemples ci-dessus), récupérer un fichier et le convertir en profil. La conversion renvoie un profil aussi contraint que possible, donc par exemple plutôt un StrictProfile qu’un Profile si possible. (Voir https://stackoverflow.com/questions/4621748/how-to-set-response-header-in-jax-rs-so-that-user-sees-download-popup-for-excel[ici] si nécessaire de détecter le nom du fichier.) (1)
EditSOC:: GUI pour éditer un profil strict. Le programme édite un fichier au format SOC. Le programme montre une colonne par électeur, et affiche dans cette colonne les alternatives de haut en bas, en commençant par la préférée. (3)
EditSOI:: GUI pour éditer un profil strict. Le programme édite un fichier au format SOI. (1)
EditSOCStruct:: Possible d’ajouter et supprimer des électeurs et des alternatives lors édition. (1)
EditSOCWeak:: Permettre les ex-æquos lors édition (édition d’un profil au lieu d’un profil strict). (1)
Results:: GUI pour visualiser les résultats des votes d’après plusieurs fonctions de choix simultanément. La visualisation s’ajoute à la fenêtre d’édition des profils : à gauche, on édite le profil, à droite, on voit les résultats. (1)
ODSProfile:: Possible d’ouvrir une feuille de calcul (au format ODS) contenant un profil tel que décrit dans EditSOC et d’y lire un profil strict ou profil non strict. Les ex-æquos sont notés en utilisant plusieurs colonnes pour un électeur donné. Utiliser Apache ODF Toolkit (voir https://github.com/oliviercailloux/Test-ODFToolkit-ODS[Test ODFToolkit-ODS]). (1)
EditBigSOC:: Le GUI permet d’afficher et d’éditer le nombre d’électeurs qui ont les mêmes préférences. Cela permet de travailler également avec de gros profils. (2)

== Autres idées
* L’utilisateur peut visualiser un profil créé dans Whale4.
* L’utilisateur peut visualiser les résultats d’une élection selon d’autres règles (cf. Whale4).
* L’utilisateur peut accéder à un profil au format xmcda-modular.

== Refs
* http://www.preflib.org/about.php[{PrefLib}]
* http://strokes.imag.fr/whale4/[Whale4]
* https://github.com/xmcda-modular[xmcda-modular]
* http://www.spliddit.org/

