= MIDO SVG

Le département MIDO propose plusieurs parcours, contenant pour certains des cours à option, avec des passerelles entre certains parcours. Il est difficile pour un enseignant extérieur (ou débutant) de se repérer dans l’offre de cours et de voir comment son cours s’articule avec les cours existants. Une manière de pallier ce problème consiste à représenter graphiquement l’offre de cours et les relations entre les cours. Cependant, de tels dessins requièrent du temps pour être bien faits, et deviennent rapidement obsolète. Ce projet vise à génération automatique de diagrammes au format SVG représentant des organigramme des cours et autres informations liées.

On pourra s’inspirer d’un https://github.com/oliviercailloux/MIDO-SVG[projet] qui s’est attaqué au problème.

== Fonctions demandées
Contract1:: Une classe DiagramPreferences qui représente les préférences d’un utilisateur concernant ce que le dessin doit montrer : filière (license, master, ou les deux) ; responsables ? ; matières ? ; enseignants ? ; prérequis ? ; tags. Les tags sont une liste de mots-clés (qui serviront à identifier les cours à montrer). Le reste sont des booléens. La classe permettra également de savoir si les informations de préférences peuvent être satisfaites : souhaiter afficher les enseignants mais pas les matières ne l’est pas.
Contract2:: Une classe Course qui représente un cours. Un cours a un nom, un enseignant (une simple chaine de caractères), une liste de cours prérequis, une URL (exemple http://formations.dauphine.fr/offre/fr-FR/fiche/A3INF/programme/A3INFAPP01), une formation et un département auxquels le cours appartient (de simples chaines de caractères dans les deux cas, temporairement).
File1:: Une classe qui permet de lire les préférences de l’utilisateur (DiagramPreferences) au format texte (de votre choix).
File2:: Une classe qui permet d’écrire les préférences de l’utilisateur.
Resources1:: Inclure dans votre classpath un fichier default-prefs.txt avec des préférences par défaut pour l’utilisateur (DiagramPreferences). Créer une classe (avec un main) qui cherche un fichier à la racine de votre projet nommé prefs.txt, et s’il n’existe pas, utilise le fichier default-prefs.txt. La classe affiche les données dans le fichier trouvé.
Resources2:: Inclure dans votre classpath un fichier example.svg (pour le moment, utilisez n’importe quel fichier SVG trouvé sur le web ; à terme il contiendra un exemple de ce que votre application peut produire). Créer un main qui ouvre ce fichier dans le navigateur de l’utilisateur.
Interfaces1:: Créer une Interface Java CourseSelector pour déterminer les cours à afficher (elle renvoie une liste de Course). On peut lui préciser la filière (license ou master), dans une autre méthode. Fusionner dans master. Dans la branche Interfaces1.1, créer une classe Drawer. On peut lui fournir une instance de CourseSelector. Elle fournit une méthode qui fournit un dessin SVG contenant simplement l’alignement des cours fournis par CourseSelector. Faites en sorte que la branche Interfaces1.1 ne contienne pas l’implémentation de l’interface.
Interfaces2:: Une classe StaticCourseSelector qui implémente CourseSelector. On peut lui fournir des données sous forme d’une liste de cours. Elle renvoie simplement les cours correspondants aux filières demandées, parmi ces données. Fusionner Interfaces2 et Interfaces1.1 dans master. Dans la branche Interfaces 2.1, créer une méthode main qui fait fonctionner le tout.

Suite des fonctions.

Dept:: Une classe Department qui représente un département (MIDO, LSO, …). Elle contient un nom et une URL (http://www.mido.dauphine.fr/ par exemple). Une classe YearOfGrade qui représente une année dans un parcours (MIAGE L3 Apprentissage par exemple), contenant un nom et une URL (http://formations.dauphine.fr/offre/fr-FR/fiche/A3INF/programme//#FRUAI0750736TPRPRA3INFAPP par exemple). Remplacer ce qui est appelé Formation ci-dessus par YearOfGrade. (1)
Draw:: Drawer effectue un dessin qui ressemble (en largement simplifié et limité aux informations stockées dans vos classes) au dessin manuel fourni en exemple. Il utilise un CourseSelector. (3)
Tags:: Une classe CoursesByTag stocke les cours associés aux tags par un utilisateur. Une autre classe permet la lecture et l’écriture de fichiers associés (au format de votre choix). (2)
Select:: Une classe CourseSelectorByTag implémente CourseSelector et sélectionne les cours par tag (en plus de satisfaire les contraintes de filières). (2)
Data:: Lecture des données de cours depuis fichier XML : s’inspirer du code existant. (3)
Prereq:: Une classe permet de lire et écrire des fichiers établissant des prérequis entre cours. (1)
GuiPref:: GUI pour éditer ses préférences d’affichage : le programme lit un fichier au démarrage, permet la modification, et écrit dans le fichier à la sortie. (3)
GuiTags:: GUI pour éditer les tags associés au cours. (À faire après le premier point GUI.) (2)
Links:: Liens sur les parcours renvoient au programme des cours. (2)

== Refs
* Voir application https://github.com/oliviercailloux/Test-SVG[Test SVG].
* Voir link:MIDO-Svg/MIDO.svg[dessin] à la main.
* CDM-fr : https://fr.wikipedia.org/wiki/Course_description_metadata https://cdm-fr.fr/

