= Teach spreadsheets

Affectation des enseignants aux cours dans le département MIDO via génération de feuilles de calcul

== Contexte
L’administration de MIDO, un département de Dauphine, utilise actuellement des feuilles de calcul pour affecter les enseignants aux cours à enseigner lors d’une année académique donnée. En vue d’une transition vers des outils plus simples d’emploi, ce projet vise à interagir automatiquement avec les feuilles de calcul intégrant les informations fournies par le département.

== Fonctions demandées
Contract1:: Une classe Course qui permet de stocker un cours (voir fichier https://github.com/oliviercailloux/projets/raw/master/Voeux/AA%20-%20Saisie%20des%20voeux%202016-2017.xls[Saisie des vœux], onglet L3) : Nom, Code Apogée, Nb heures CM, Nb heures TD, Nb heures CMTD, Nb heures TP, Nb groupes CM / TD / etc., et l’année d’études dans laquelle le cours s’insère (L3 Informatique, M1 Mathématiques, L3 apprentissage, …). (0,5)
Contract2:: Une classe CoursePref qui stocke des préférences d’un enseignant pour un cours : elle permet d’indiquer une préférence pour le CM, TD, CMTD, TP (A, B, C ou absent, pour chacun). (0,5)
File1:: Une classe qui permet d’écrire une liste de cours au format CSV. (1)
File2:: Une classe qui permet de lire une liste de cours au format CSV. (1)
Resources1:: Inclure dans votre class path un fichier de cours start-courses.csv. Créer une méthode main qui affiche le contenu du fichier. (0,5)
Resources2:: Inclure dans votre class path un exemple de fichier de saisie des vœux. Créer un main qui ouvre le document à l’aide de Apache ODFToolkit (voir https://github.com/oliviercailloux/Test-ODFToolkit-ODS[Test ODFToolkit-ODS]) et le referme aussitôt, et affiche si le document a bien pu être ouvert. (1)
Interfaces1:: Créer une Interface Java SpreadsheetReader pour lire des données d’une feuille de calcul : on lui fournit une position (par exemple A1) et elle renvoie ce qui s’y trouve. Une autre méthode permet de détecter les barres obliques (voir fichier de saisie des vœux). On peut aussi lui préciser une feuille courante. Fusionner dans master. Dans la branche Interfaces1.1, créer une classe SpreadsheetShower. On peut lui fournir une instance de SpreadsheetReader. Elle fournit une méthode qui demande en boucle à l’utilisateur, sur l’entrée standard, des positions, et lui renvoie ce qui s’y trouve. Une autre méthode permet de préciser le fichier d’entrée. Faites en sorte que la branche Interfaces1.1 ne contienne pas d’implémentation de SpreadsheetReader. (1,5)
Interfaces2:: Une classe ODSReader qui implémente SpreadsheetReader. On peut lui fournir un fichier d’entrée. Fusionner Interfaces2 et Interfaces1.1 dans master. Dans la branche Interfaces 2.1, créer une méthode main qui fait fonctionner le programme de discussion avec l’utilisateur. (1,5)
ReadCourses:: Lecture d’un fichier de saisie des vœux. (Bien entendu, la lecture doit fonctionner quel que soit le nombre d’onglets et de cours.) Utilise l’interface SpreadsheetReader et l’implémentation ODSReader (éventuellement étendues). (2)
WriteCourses:: Classe permettant d’écrire un fichier de saisie des vœux, non rempli, à partir d’une liste de cours. Le programme se base sur un modèle disponible dans le class path, qui reprend les deux premiers onglets du fichier exemple.. (2)
ReadPrefs:: Classe permettant de lire les préférences d’un enseignant, à partir d’un fichier de saisie de vœux rempli. Une classe TeacherPref permet de stocker un ensemble de CoursePref, un enseignant, une association de chaque cours à un nombre de groupes souhaités. La classe lit également le nombre d’années enseignées. (Cf. WritePrefs) (1)
Teacher:: Une classe Enseignant qui contient les informations nécessaires pour remplir les deux premiers onglets. Une classe ReadTeacher qui lit les informations depuis un fichier de préférence XML Java. (1)
WritePrefs:: … écriture. Facultativement, on peut fournir à la classe un Enseignant (contenant des informations objectives le décrivant : nom, prénom, coordonnées), auquel cas elle écrit également dans les cases correspondantes. Facultativement, on fournit également à la classe une association entre les cours et le nombre d’années enseignées, qu’elle écrit donc également. (1)
Matching:: Classe qui stocke les affectations des enseignants aux cours pour une année donnée, en considérant la possiblité qu’un enseignant soit affecté à plusieurs cours, et sachant qu’un cours qui a plusieurs groupes aura autant de TDs, donc possiblement autant d’enseignants différents (c’est un maximum : un enseignant peut gérer plusieurs groupes de TDs). (1)
Merge:: Classe créant une feuille de calcul synthétisant un ensemble d’informations de préférences, à partir des préférences de plusieurs enseignants et à partir des affectations (de l’année précédente). Voir https://github.com/oliviercailloux/projets/raw/master/Voeux/Fichier%20Agr%C3%A9g%C3%A9.pdf[Fichier Agrégé.pdf]. (2)
GUICourses:: GUI pour éditer les cours d’une année donnée. Lit et écrit un fichier de type Saisie des vœux. (3)
ReadXLS:: Une classe XLSReader qui implémente SpreadsheetReader en utilisant Apache POI. Il faudra pouvoir choisir ODSReader ou XLSReader pour tous les cas d’utilisation ci-dessus. (2)
DoPrefs:: GUI pour indiquer ses préférences, étant donné un enseignant, une information d’affectation, un ensemble de cours, un nombre d’années d’enseignement pour chaque cours. Le programme génère un fichier de saisie des vœux rempli. (3)
FileMatching:: Lecture et écriture d’une affectation d’enseignants aux cours pour une année donnée. Voir https://github.com/oliviercailloux/projets/raw/master/Voeux/services%20MIDO.xls[services MIDO], onglet « donnees ». Le programme écrit dans un fichier basé sur un modèle stocké dans le class path, contenant le tableau croisé dynamique de l’onglet Affectations. (Ajouter les champs manquants aux classes correspondantes.) (1)
DoMatch:: GUI pour affecter. En partant d’une affectation donnée. Affichage d’un enseignant choisi par une boite de texte : liste des cours auxquels il est affecté, type (CM / TD / …), nombre d’heures. Affichage du total d’heures en bas. Le GUI permet la modification. (2)
ServiceCard:: Étant donné une affectation, génération d’un ensemble de fiches de service (une par enseignant) dans un répertoire donné. Voir https://github.com/oliviercailloux/projets/raw/master/Voeux/Fiche%20de%20service.png[Fiche de service]. (1)

