= XM-GUI

Interface graphique permettant d’éditer des problèmes de théorie de la décision et d’envoyer ces problèmes à des services web.

== Contexte
Une série de services web ouverts permet d’utiliser les méthodes d’aide multicritère à la décision. Ils reposent sur le format http://www.decision-deck.org/xmcda/[XMCDA] et sur le logiciel http://www.diviz.org/[diviz], qui permet l’invocation des services sans devoir programmer. L’utilisateur doit cependant fabriquer à la main les fichiers XML d’entrée (ou convertir du CSV), et plus généralement il n’existe pas d’intégration des outils dans un logiciel très simple d’emploi.

Pour comprendre l’usage actuel de ces services, suivez le https://www.diviz.org/tutorial.diviz.html[tutoriel] diviz. Pour comprendre le format de données utilisé, examinez l’exemple https://github.com/oliviercailloux/Six-real-cars/[Six real cars] au format XMCDA v2 (X2).

On repartira d’un https://github.com/oliviercailloux/XM-GUI[projet] existant, qui permet de manipuler des alternatives, des critères, des évaluations à l’aide d’une interface graphique et de les enregistrer au format X2, et d’appeler un service web à l’aide de ces données.

== À envisager
* Améliorer les GUI existants permettant d’éditer un ensemble d’alternatives, de critères, et leurs évaluations.
* GUI pour créer un AlternativesRanking contenant un ensemble d’alternatives et un rang associé à chaque alternative (voir code existant ; améliorer classe `AlternativesRanking`)
* Classe permettant d’appeler le service web https://www.decision-deck.org/ws/wsd-rankAlternativesValues-RXMCDA.html[wsd-rankAlternativesValues-RXMCDA] (voir https://github.com/oliviercailloux/test-call-xmcda-ws[test-call-xmcda-ws] et code existant) et d’obtenir le numéro de ticket à partir d’une instance de `AlternativesRanking`, puis le résultat à partir du ticket.
* Variante du GUI pour éditer des évaluations, l’ensemble des alternatives et des critères étant fixé.
* GUI permettant d’éditer des listes d’alternatives, des listes de critères, des évaluations, des rankings, chacun associés à un nom (alternatives 1, alternatives 2, criteria 1, …). Le GUI Evaluations permet de préciser en entrée quelles alternatives et quels critères sont utilisés.
* GUI qui montre le résultat de l’appel au service web `rankAlternativesValues` et se rafraichit automatiquement lorsque l’entrée change. Il permet également de sélectionner l’entrée adéquate s’il y en a plusieurs
* Mécanisme général à base de `XMCDAProducer`, un `XMCDAProducer` ayant un nom et consommant et produisant une liste de types, parmi Alternatives, Criteria, Evaluations, AlternativesRanking, et étant associé à un GUI. Par exemple le `XMCDAProducer` `performances` consomme `Alternatives` et `Criteria` et produit `Evaluations`. Au démarrage on fournit une liste de `XMCDAProducer` possibles. L’utilisatrice peut afficher autant de `XMCDAProducer` qu’elle souhaite.
* L’appel au service web est aussi un `XMCDAProducer`.

== Ensuite
* Généraliser les appels aux services web. Voici une ébauche d’approche possible.
* Créer une classe XMCDASubSchema. Une instance de cette classe décrit les informations nécessaires pour appeler un service web XMCDA donné. Il y aura une instance par service web. Ces informations sont décrites dans le fichier descripteur diviz description.xml (http://www.decision-deck.org/ws/wsd-rankAlternativesValues-RXMCDA.html[exemple]). Les données consistent en une association entre des noms (String représentant le nom de l’entrée) et des types XMCDA (le "xmcda main tag"). Les types XMCDA possibles sont représentés à l’aide d’un Enum XMCDAType (inutile de prévoir toutes les possibilités, incluez un certain nombre de types possibles pour illustrer). Exemple : Alternative, Value, AlternativesValues, etc. La documentation autre présente dans le fichier descripteur n’est pas reprise dans la classe.
* Créer une classe XMCDADataDescription dont une instance contient un ensemble de données XMCDA disponibles dans un certain contexte, soit une List de XMCDAType.
* Créer une classe XMCDAWebServices qui reçoit à la création un ensemble de XMCDASubSchema décrivant des services web diviz et qui, lorsqu’on lui envoie une XMCDADataDescription, renvoie le sous-ensemble de XMCDASubSchema compatibles avec les données, c-à-d ceux qui peut être appelé étant donné les données disponibles : ceux dont toutes les informations requises sont disponibles.
* Classe XMCDAData dont une instance contient une List de Node, décrivant un ensemble de données XMCDA.
* Classe XMCDAServiceCaller permettant d’appeler un service web XMCDA. On lui envoie l’url et le XMCDASubSchema d’un service web et un XMCDAData décrivant les données, et elle renvoie un numéro de ticket. Une autre méthode permet, étant donné le ticket, de récupérer un XMCDAData contenant le résultat de l’appel. Essayer d’abord de faire fonctionner 
* Classe XMCDASimpleServiceCaller à laquelle on envoie une url, un XMCDASubSchema et un XMCDAData, et qui renvoie un Future permettant d’obtenir le résultat attendu. La tâche créée interroge le service web (pour savoir si le travail est terminé) d’abord toutes les deux secondes pendant les premières dix secondes, puis toutes les dix secondes pendant la première minute, puis toutes les minutes.
* Parsing d’un fichier de description diviz description.xml (http://www.decision-deck.org/ws/wsd-rankAlternativesValues-RXMCDA.html[exemple]) et création d’un XMCDASubSchema correspondant à l’entrée et un correspondant à la sortie.
* Prendre en charge Alternative, Criterion, et un ensemble d’évaluations au format https://github.com/xmcda-modular[XMCDA-modular] (XM, utiliser la bibliothèque JAXB) : sérialisation et déserialisation. On pourra donc facilement convertir une entrée X2 en sortie XM, ou l’inverse.
* Serveur (facade) permettant d’appeler un service web existant à partir de données XM.

