= Dauphine Open Data

Application de mise à disposition de données de Dauphine

== Contexte
L’université Paris-Dauphine crée et met à jour de nombreuses données publiques, qui sont parfois mises à disposition uniquement via son site web, voire parfois non mises à disposition et simplement conservées dans des bases de données.

Le mouvement open data considère que les données bénéficient d’une exposition maximale, dans des formats facilement lisibles par des machines. Entre autres bénéfices, cette approche facilite la réutilisation et l’innovation.

Ce projet a pour but de créer une plate-forme qui servira à la mise à disposition de certaines données publiques de Paris-Dauphine. Il visera à mettre également à disposition certaines données non publiques après authentification. Par exemple, un enseignant a droit d’accès aux adresses e-mail des étudiants qui suivent son cours, mais ces données ne sont pas publiques.

//Ce projet sera développé en collaboration avec la Direction des Systèmes d’Information (DSI) de Dauphine.

Possibilité de réutiliser les classes d’un https://github.com/oliviercailloux/Teach-planning[projet] existant concernant l’enseignement et les cours. Mentionner systématiquement de tels emprunts, afin de respecter le droit d’auteur.

== Fonctions demandées
Course:: Objet Course pour représenter un cours de Dauphine. S’inspirer du modèle dans le projet existant et des informations contenues dans le Référentiel de l’Offre de Formation (ROF) de Dauphine au format CDM-fr (voir https://raw.githubusercontent.com/oliviercailloux/projets/master/Voeux/OF_MEA5STI.xml[exemple XML]), à simplifier éventuellement pour conserver l’information essentielle. Documenter vos choix. Permettre encodage d’un cours par une représentation textuelle. L’identifiant d’un cours doit être un String. (1)
Basics:: Objets Person pour représenter un étudiant ou un enseignant (voir informations contenues dans l’ link:https://www.ent.dauphine.fr/Annuaire/index.php?param0=fiche&param1=ocailloux[annuaire] et dans ROF). Objet Planning pour représenter les liens horaires et liens entre cours et enseignant (tel enseignant a une séance de tel cours à telle heure). Voir informations contenues dans le planning en ligne de Dauphine (chercher Cailloux). Identifier une personne par son login Dauphine, un identifiant de 8 caractères. Documenter vos choix. (1)
Triple:: Objet Triple contenant : (subject: String, predicate: String, object: String). (Plus : Gérez ces triplets avec une bibliothèque RDF.) Permettez encodage et décodage en texte (ou JSON), y compris d’une liste de tels triplets. (0,5)
VCal:: Permettre encodage d’une ou plusieurs entrées de planning, au format VCal. Fournir des tests unitaires. (1)
VCard:: Permettre encodage d’une ou plusieurs personnes, au format VCard. Fournir des tests unitaires. (1)
BasicServlets:: getCourse(id): Course. getPerson(id Dauphine): Person (VCard). getPlanning(id Dauphine): VCal (toutes les entrées correspondant à cette personne). Ces données (supposées venir de Dauphine centrale) sont en lecture seule. On peut en outre associer une information à n’importe quel objet : addTriple(subject, predicate, object), où subject doit correspondre à un id d’un objet dans vos données ; removeTriple(subject, predicate, object) ; getData(subject): List<Triple<subject, predicate, object>>. (1) (Vous vous arrangerez pour que tous les id dans votre modèle soient différents.)
BasicClient:: Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande, la visualisation des informations de base de Course et Person, et l’ajout de triplets associés. (1)
Lib:: Isoler la partie bibliothèque du reste du code. La publier comme un projet Maven indépendant (suffixer le nom du projet de -lib) et faire dépendre le reste du code de cette bibliothèque. Isoler la partie client du reste du code, publier comme un projet indépendant (ProjectName-client). Publier la partie serveur comme un projet indépendant (ProjectName). (1,5)
ObjectsXML:: Encoder / décoder une partie de vos objets du modèle en XML. Repartir du schéma CDM-fr, à simplifier éventuellement. (1)
ObjectsJSON:: Encoder / décoder le reste de vos objets du modèle en JSON. (0,5)
ExtBasicServlets:: Étendre servlets existants pour renvoyer à la demande du XML ou JSON en plus des formats déjà supportés. Transformer en JAX-RS. Cookie permet de mémoriser un id person, il est utilisé si l’id person n’est pas fourni, pour les servlets qui requièrent ce paramètre. (1)
Gather:: Récupérer les données depuis l’annuaire si elles ne sont pas déjà dans votre modèle, ou si elles sont trop vieilles, au moment de la requête. Votre modèle stocke ces données et leur date. (Parser le HTML selon le standard DOM.) Récupérer les informations du planning, selon la même approche. (1)
Online:: Faire tourner le serveur en ligne grâce au service d’IBM. (1)
PIGateway:: Offrir des servlets pour refléter les servlets offerts par le projet Poleinfo. Vos servlets relayent simplement les appels au serveur Poleinfo. Ils sont accessibles aux mêmes adresses que le projet Poleinfo mais avec le préfixe /PI. (On ne se contente pas de réécriture d’URL car ces services seront étendus par la suite.) (0,5)
SetDB1:: Implémenter une entité JPA et les méthodes permettant d’écrire et de lire depuis la BD les cours et triplets. (1)
SetDB2:: Même chose pour le reste du modèle : Person et Planning. (1)
UseDB:: Modifier les servlets pour qu’ils écrivent dans et lisent la BD. (1)
SOAP:: Transformer certains servlets pour en faire des services SOAP. (1)
SOAPClient:: Transformer les clients pour en faire des clients SOAP. (1)
AuthDoc:: Documenter en détail et clairement le mécanisme d’authentification sur le CAS de Dauphine. Le document, au format Asciidoc, doit être compréhensible par un étudiant ayant les prérequis pour ce cours mais non expert en programmation web. Illustrer avec une application de démo, de préférence de code ouvert, sur GitHub, si permis par la DSI. À effectuer en partenariat avec la DSI : contacter Jean-Christophe GAY, de ma part (contacts sur l’annuaire de Dauphine). (2)

== Autres fonctionnalités
* Mécanisme d’authentification en lien avec le CAS de Dauphine (en partenariat avec la DSI).
* Récupération des données de planning plus propres (en partenariat avec la DSI).
* Prise en compte des remarques suite à review code (sécurité & qualité) par la DSI.
* Menu du CROUS ? (Seulement trouvé http://www.dauphine.fr/fr/universite/campus/campus-porte-dauphine/restauration.html[ceci] et http://www.mso.dauphine.fr/fileadmin/mediatheque/mso/images/Menu_GRILL.pdf[menu] utilisé précédemment.)

== Authentification
Voici les informations dont je dispose concernant l’authentification.

Dauphine utilise le CAS Apéréo, la partie visible de Passeport.
Il y a (ou avait) aussi un système de « proxy tickets ». Mais ce système est peu à peu démantelé par la DSI car développement jugé trop compliqué.

CAS sur intranet Dauphine, accessible uniquement depuis une machine sur domaine dauphine.fr. Renommer “localhost” (dans fichier /etc/hosts ?) en “myservice.dauphine.fr”. Il faut s’adresser au CAS à partir du port 80 ou 443, donc il faut changer la configuration de Glassfish.
Connexion au CAS de test : appeler la page https://passeport.qualif.dauphine.fr/cas/login?service=http://myservice.dauphine.fr/open_data/login avec une url de service de la forme http://myservice.dauphine.fr. Le CAS envoie un ticket à l’application (il redirige l’utilisateur vers http://myservice.dauphine.fr/open_data/login?ticket=ST-2788-n1aHBsxSUlQ1V9JuKGYS-passeport.dauphine.fr ?). On peut ensuite demander d’autres informations sur la connexion via "https://passeport.qualif.dauphine.fr/cas/p3/serviceValidate?service=http://myservice.dauphine.fr/open_data/login&ticket="+ ticket + "&format=json".

== Refs
* CDM-fr : https://fr.wikipedia.org/wiki/Course_description_metadata https://cdm-fr.fr/
* https://planning.dauphine.fr/direct/index.jsp?data=767bdec461375cab4e1db9324b2b295a450c06489b0765a5db849b3aa84b0275dead10e6e85e1fd6e0fa50826f0818af8d95b75bb9e1e194[Planning] Dauphine 2017

