= MIDO SVG

Le département MIDO propose plusieurs parcours, contenant pour certains des cours à option, avec des passerelles entre certains parcours. Il est difficile pour un enseignant extérieur (ou débutant) de se repérer dans l’offre de cours et de voir comment son cours s’articule avec les cours existants. Une manière de pallier ce problème consiste à représenter graphiquement l’offre de cours et les relations entre les cours. Cependant, de tels dessins requièrent du temps pour être bien faits, et deviennent rapidement obsolète. Ce projet vise à génération automatique de diagrammes au format SVG représentant des organigramme des cours et autres informations liées.

On repartira d’un https://github.com/oliviercailloux/MIDO-SVG[projet] qui a entamé une résolution du problème.

== À envisager
* Passer à JUnit 5
* Utiliser https://github.com/oliviercailloux/JARiS[JARiS] pour lire la clé d’API pour accès à ROF, le Référentiel des Offres de Formation de Dauphine (obtenir l’accès via la DSI)
* On peut afficher, en ligne de commande, la liste des cours de la L3 MIAGE alternance récupérée à partir de ROF (voir `Querier` et  https://github.com/Dauphine-MIDO/plaquette-MIDO[plaquette-MIDO]). Simplifier `Subject` pour ce faire (sans les informations de position graphique), ou créer une classe `Course`. 
* Généraliser pour permettre l’affichage de la M1 MIAGE alternance, ou autre formation de MIDO. Simplifier `Formation` ou créer `Training` pour ce faire, une instance contenant une seule année (par exemple la L3).
* Un cours a une URL qui envoie vers le programme sur le site de Dauphine
* Pouvoir récupérer et afficher les formations, de L3 à M2 alternance, depuis la ligne de commande, selon les options précisées parmi L3, M1, M2.
* Une formation a une URL (https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises/formation par exemple) et un entier indiquant le niveau d’étude (de BAC+1 à BAC+5)
* Concevoir une classe `Positioner` qui reçoit une taille de police et un ensemble de formations, et calcule pour chaque cours la taille (longueur et largeur, entiers) requise pour afficher le cours, et pour chaque formation, la taille requise pour afficher la formation (selon les tailles des cours). Étudier pour ce faire la logique mise en place dans le package `svg_generator`.
* `Positioner` doit pouvoir renvoyer la position absolue d’un cours ou d’une formation, en imaginant qu’on les empile (cf. dessins existants et https://github.com/oliviercailloux/projets/blob/master/MIDO%20SVG/MIDO.svg[dessin] à la main).
* Simplifier les classes de dessin actuelles pour leur faire dessiner à partir d’un `Positioner`. Voir aussi application https://github.com/oliviercailloux/Test-SVG[`Test SVG`] et `2D Library`.
* Ajouter les responsables, les enseignants, etc.
* Une classe `DiagramPreferences` qui représente les préférences d’un utilisateur concernant ce que le dessin doit montrer : filière (license, master, ou les deux) ; responsables ? ; enseignants ? ; prérequis ? (des booléens).
* Donner au `Positioner` des options indiquant si on veut les responsables, les enseignants, etc. (cf. point ci-dessus).
* Calcul automatique de l’espace entre les cours et formation pour centrer le dessin sur une taille donnée ; calcul automatique de la police (partant d’une taille donnée et en réduisant si nécessaire) pour que toutes les informations tiennent sur un canevas donné
* Pouvoir lire et écrire les préférences de l’utilisateur (`DiagramPreferences`) au format Json.
* Inclure un fichier `config.json` avec des préférences par défaut pour l’utilisateur (`DiagramPreferences`).
* Généraliser à d’autres départements (LSO, …)
* GUI pour éditer ses préférences d’affichage : le programme lit le fichier au démarrage, permet la modification, et écrit dans le fichier
* GUI pour générer le dessin à partir de ses préférences : on édite ses préférences et ça re-génère automatiquement un dessin
* Étudier la possibilité d’inclure une information de pré-requis entre cours
* Un serveur web qui renvoie un diagramme à la demande
* Génération de diagramme en PNG ou autre

