= Teach spreadsheets

Affectation des enseignants aux cours dans le département MIDO via génération de feuilles de calcul

== Contexte
L’administration de MIDO, un département de Dauphine, utilise actuellement des feuilles de calcul pour affecter les enseignants aux cours à enseigner lors d’une année académique donnée. En vue d’une transition vers des outils plus simples d’emploi, ce projet vise à interagir automatiquement avec les feuilles de calcul intégrant les informations fournies par le département.

On repatira d’un https://github.com/oliviercailloux/Teach-spreadsheets[projet] existant, capable de lire des préférences exprimées dans des feuilles de calcul et d’en écrire de nouvelles. L’objectif principal sera de l’étendre de façon à ce qu’il permette de travailler avec Office 365 (c-à-d dans le cloud au lieu de localement uniquement)

== À envisager
* L’application lit les données de préférences à partir d’une feuille de calcul présente dans le répertoire courant, crée une feuille Microsoft Excel 365 et y entre les données de préférences lues (s’inspirer de https://universitedauphine-my.sharepoint.com/:x:/r/personal/olivier_cailloux_lamsade_dauphine_fr/_layouts/15/Doc.aspx?sourcedoc=%7B9bff1ac1-1b54-4b6c-a2d8-53094178d25d%7D&action=edit&wdPreviousSession=0b59b668-1ca8-44ac-a8b2-8273183ac24a[cet exemple] utilisé pour cette année)
* L’application lit plusieurs feuilles en entrée, et compile les données de préférences dans la feuille 365
* Si une feuille 365 existe déjà, l’application écrase les informations dans les cellules correspondantes ; et indique dans un nouvel onglet les modifications apportées
* L’application lit les affectations actuelles dans la feuille 365 et compile, dans un onglet particulier, les affectations pour chacun, en indiquant le total d’heures affectées et désirées pour chacun.
* L’application affiche la différence entre le nombre d’heures total désiré et le total affecté, pour chaque enseignant, dans chaque cellule où il apparait, par exemple : "[− 30h]".
* L’application génère un résumé de toutes les affectations, par cours (cf. https://github.com/oliviercailloux/projets/raw/master/Teach%20spreadsheets/Affectations.ods[exemple]), pour diffusion aux enseignants
* Accéder aux données des cours de l’année passée pour indiquer les responsables précédents dans 365 (ou modifier si déjà indiqués)
* (Avec la Direction des Systèmes d’Information de Dauphine) Accéder aux cours prestés l’année passée : nombre d’heures, nombre de groupes, etc. Générer une feuille 365 ressemblant aux feuilles de collecte des préférences à l’aide de ces données.

