= J-Confs

Outil de gestion de déplacement en conférence.

== Contexte

Ce projet a pour but d’aider un chercheur et l’administration à organiser les déplacements en conférence, en manipulant des formats de calendrier, en manipulant des cartes et des APIs de récupération de prix pour planifier l’itinéraire, … On fournira également éventuellement des outils annexes pour simplifier certaines tâches administratives récurrentes telles que des remplissages de formulaires.

On repartira d’un https://github.com/oliviercailloux/J-Confs[projet] existant. Il permet de stocker et lire des conférences dans un calendrier partagé en ligne ; et implémente une logique partielle d’affichage de cartes des lieux de conférence ; il permet également de générer des documents sur base des coordonnées d’un chercheur (cependant, le système de récupération des données est cassé suite à un changement de fonctionnement de l’annuaire de Dauphine).

== À envisager
* Fix tests that fail
* Utiliser https://github.com/oliviercailloux/JARiS[JARiS] pour lire la clé d’API pour accès aux services de calendrier en ligne ou LocationIQ
* Améliorer ou compléter documentation, implémentation, tests du package calendar pour permettre récupération et édition d’entrées calendrier sur Fruux et NextCloud ; si nécessaire.
* GUI pour visualiser les conférences du calendrier en ligne
* GUI pour ajouter une conférence au calendrier en ligne
* GUI pour modifier une conférence du calendrier en ligne
* S’assurer que `CalendarOnline` stocke des conférences dans un format qui est compris par les logiciels de manipulation de calendriers tels que `Evolution`. Documenter quels champs du standard iCal sont utilisés, en particulier, comment représenter un point précis sur le globe (latitude, longitude, adresse textuelle)
* Stocker une `Address` (point avec une description et des coordonnées) dans conférence au lieu ds champs de localisation actuels (`country`, `city`), pour une localisation précise
* Calcul en ligne de commande d’un trajet de Paris à une ville d’europe continentale reliée directement à Paris (exemple : Berlin, Bruxelles), en train, avec prix. Commencer par rédiger un rapport, au format Asciidoctor, investigant les API en ligne pour ce faire. (Essayer la Deutshe Bahn)
* GUI pour montrer le trajet
* Étendre aux trajets à plusieurs points (avec changements)
* Étendre aux trajets en avion ; en voiture
* Étendre aux trajets multi-modaux
* Le trajet est associé à une URL qui permet de l’afficher sur une carte (https://www.openstreetmap.org/directions?engine=osrm_car&route=48.857%2C2.352%3B52.517%2C13.389#map=7/50.716/7.866[Exemple])
* Améliorer éventuellement documentation de https://github.com/mapsforge/mapsforge[Mapsforge] (https://www.javadoc.io/doc/org.mapsforge/mapsforge-map-reader/0.8.0/index.html[Javadoc]), étudier la possibilité de l’utiliser pour afficher le trajet directement
* Étendre la fonctionalité d’enregistrement d’un prix (`registrationFee`) d’une conférence pour permettre des prix différenciés : student price, early registration fee, member price, …
* Étudier la possibilité d’utiliser https://geotools.org/[`GeoTools`] pour calculer des distances ou temps de parcours en voiture entre endroits sur le globe, ou convertir entre adresses et coordonnées, en vue de remplacer LocationIQ, et comparer à la solution actuelle
* Nettoyer ressources (16 MB dans src/main/resources/io/github/oliviercailloux/jconfs)
* Chercher les informations concernant un chercheur à l’aide de Supann, cf. https://github.com/Dauphine-MIDO/plaquette-MIDO[Plaquette MIDO]
* Étudier existence d’une API plus moderne pour manipuler des documents OpenDocument
* Modifier canevas existant LibreOffice Writer, insérer des champs d’utilisateur tels que Researcher_name ou Conference_name (dans LibreOffice : menu Insertion / Champ / Autres champs / Variables), et faire en sorte que ces champs soient mis à la bonne valeur
* GUI pour générer un document LibreOffice (cf. ci-dessus)
* L’ensemble du calendrier doit pouvoir être envoyé sur un dépot existant GitHub créé (manuellement) à cet effet. Après modification de conférences (à la sortie de l’application ou toutes les 30 minutes), le nouveau calendrier est envoyé sur le dépôt existant, pour sauvegarde (permet de restaurer une version précédente en cas d’effacement maladroit, par exemple)
* L’utilisateur peut ajouter des entrées de dépenses (par exemple, dépenses sur place) qui s’ajoutent à la note
* Serveur web qui renvoie un canevas LibreOffice sur base du login d’un chercheur
* Génération du formulaire annuel de demande de PRES (voir https://github.com/oliviercailloux/projets/blob/master/LAMSADE/PRES.pdf[canevas] PRES), d’après données passées en paramètres / fournies par interface graphique / récupérée depuis fichier / récupérée depuis internet
* L’utilisateur peut entrer son mot de passe de son compte e-mail @dauphine. Le logiciel le stocke en suivant le mécanisme de conservation des données secrètes de l’OS.
* Réception des demandes scannées envoyées sur l’e-mail du chercheur (reconnaissable par l’adresse expéditeur : \photocopieur@lamsade.dauphine.fr), à la demande de l’utilisateur.
* Envoi demande par e-mail.
* Pouvoir publier son trajet, en vue par exemple de voyager avec ses collègues

